/**
 * POST /api/state-intelligence/strategy-engine/export
 *
 * Stateless PPTX export for a generated strategy. The client posts back the
 * `GeneratedStrategy` payload it already has; we map it to SlideSpec[] and
 * reuse the proposal-builder deck writer (pptxgenjs, native charts, Vercel-safe).
 * Nothing is persisted — the strategy is regenerated on demand, so there's no
 * row to fetch.
 *
 * Errors:
 *   400 — invalid body / missing plan
 *   401 — unauthenticated
 *   500 — PPTX generation failure
 */

import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import {
  getAuthenticatedUser,
  resolveBrandingFromRequest,
} from "@/lib/proposal-builder/server";
import { buildProposalPptx } from "@/lib/proposal-builder/pptx";
import { strategyToSlides, strategyDeckFilename } from "@/lib/strategy-engine/slides";
import type { GeneratedStrategy } from "@/lib/strategy-engine/types";

// pptxgenjs is Node-only — pin this handler to the Node runtime.
export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  const supabase = await createClient();
  const auth = await getAuthenticatedUser(supabase);
  if (!auth) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: GeneratedStrategy;
  try {
    body = (await req.json()) as GeneratedStrategy;
  } catch {
    return NextResponse.json({ error: "Request body must be JSON" }, { status: 400 });
  }

  if (!body?.plan?.archetype || !body?.prose) {
    return NextResponse.json({ error: "Missing strategy plan or prose" }, { status: 400 });
  }

  const branding = await resolveBrandingFromRequest(req);
  const slides = strategyToSlides(body);

  let buffer: Buffer;
  try {
    buffer = await buildProposalPptx({
      title: `${body.plan.state_name} ${body.plan.tort_label} Media Strategy`,
      description: `${body.voice}-facing · generated by Legal Marketing Intelligence`,
      slides,
      branding,
    });
  } catch (e) {
    return NextResponse.json(
      { error: "PPTX generation failed", details: e instanceof Error ? e.message : String(e) },
      { status: 500 },
    );
  }

  const filename = strategyDeckFilename(body.plan);
  return new NextResponse(new Uint8Array(buffer), {
    status: 200,
    headers: {
      "Content-Type":
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Content-Length": String(buffer.length),
      "Cache-Control": "no-store",
    },
  });
}
