-- Seed pi_metros for all 50 states + DC (Search Advertising Landscape).
-- ~3 major metros per state. AL/CA/FL already seeded in
-- 20260417120000_add_pi_search_tables.sql; ON CONFLICT no-ops them.
-- pi_search_daily.py loops every pi_metros row and auto-builds
-- pi_search_observations + pi_competitor_profiles, so the get_pi_* RPCs
-- (and each state page's Search Advertising Landscape) populate on the
-- next run. searchapi_location is Google's canonical geotarget name.

INSERT INTO public.pi_metros (state_abbr, metro_name, metro_label, searchapi_location) VALUES
  ('AL', 'Birmingham', 'Birmingham, AL', 'Birmingham, Alabama, United States'),
  ('AL', 'Montgomery', 'Montgomery, AL', 'Montgomery, Alabama, United States'),
  ('AL', 'Huntsville', 'Huntsville, AL', 'Huntsville, Alabama, United States'),
  ('AK', 'Anchorage', 'Anchorage, AK', 'Anchorage, Alaska, United States'),
  ('AK', 'Fairbanks', 'Fairbanks, AK', 'Fairbanks, Alaska, United States'),
  ('AK', 'Juneau', 'Juneau, AK', 'Juneau, Alaska, United States'),
  ('AZ', 'Phoenix', 'Phoenix, AZ', 'Phoenix, Arizona, United States'),
  ('AZ', 'Tucson', 'Tucson, AZ', 'Tucson, Arizona, United States'),
  ('AZ', 'Mesa', 'Mesa, AZ', 'Mesa, Arizona, United States'),
  ('AR', 'Little Rock', 'Little Rock, AR', 'Little Rock, Arkansas, United States'),
  ('AR', 'Fayetteville', 'Fayetteville, AR', 'Fayetteville, Arkansas, United States'),
  ('AR', 'Fort Smith', 'Fort Smith, AR', 'Fort Smith, Arkansas, United States'),
  ('CA', 'Los Angeles', 'Los Angeles, CA', 'Los Angeles, California, United States'),
  ('CA', 'San Francisco', 'San Francisco, CA', 'San Francisco, California, United States'),
  ('CA', 'San Diego', 'San Diego, CA', 'San Diego, California, United States'),
  ('CO', 'Denver', 'Denver, CO', 'Denver, Colorado, United States'),
  ('CO', 'Colorado Springs', 'Colorado Springs, CO', 'Colorado Springs, Colorado, United States'),
  ('CO', 'Aurora', 'Aurora, CO', 'Aurora, Colorado, United States'),
  ('CT', 'Bridgeport', 'Bridgeport, CT', 'Bridgeport, Connecticut, United States'),
  ('CT', 'New Haven', 'New Haven, CT', 'New Haven, Connecticut, United States'),
  ('CT', 'Hartford', 'Hartford, CT', 'Hartford, Connecticut, United States'),
  ('DE', 'Wilmington', 'Wilmington, DE', 'Wilmington, Delaware, United States'),
  ('DE', 'Dover', 'Dover, DE', 'Dover, Delaware, United States'),
  ('DE', 'Newark', 'Newark, DE', 'Newark, Delaware, United States'),
  ('DC', 'Washington', 'Washington, DC', 'Washington, District of Columbia, United States'),
  ('FL', 'Miami', 'Miami, FL', 'Miami, Florida, United States'),
  ('FL', 'Tampa', 'Tampa, FL', 'Tampa, Florida, United States'),
  ('FL', 'Jacksonville', 'Jacksonville, FL', 'Jacksonville, Florida, United States'),
  ('GA', 'Atlanta', 'Atlanta, GA', 'Atlanta, Georgia, United States'),
  ('GA', 'Augusta', 'Augusta, GA', 'Augusta, Georgia, United States'),
  ('GA', 'Savannah', 'Savannah, GA', 'Savannah, Georgia, United States'),
  ('HI', 'Honolulu', 'Honolulu, HI', 'Honolulu, Hawaii, United States'),
  ('HI', 'Hilo', 'Hilo, HI', 'Hilo, Hawaii, United States'),
  ('HI', 'Kailua', 'Kailua, HI', 'Kailua, Hawaii, United States'),
  ('ID', 'Boise', 'Boise, ID', 'Boise, Idaho, United States'),
  ('ID', 'Meridian', 'Meridian, ID', 'Meridian, Idaho, United States'),
  ('ID', 'Nampa', 'Nampa, ID', 'Nampa, Idaho, United States'),
  ('IL', 'Chicago', 'Chicago, IL', 'Chicago, Illinois, United States'),
  ('IL', 'Rockford', 'Rockford, IL', 'Rockford, Illinois, United States'),
  ('IL', 'Springfield', 'Springfield, IL', 'Springfield, Illinois, United States'),
  ('IN', 'Indianapolis', 'Indianapolis, IN', 'Indianapolis, Indiana, United States'),
  ('IN', 'Fort Wayne', 'Fort Wayne, IN', 'Fort Wayne, Indiana, United States'),
  ('IN', 'Evansville', 'Evansville, IN', 'Evansville, Indiana, United States'),
  ('IA', 'Des Moines', 'Des Moines, IA', 'Des Moines, Iowa, United States'),
  ('IA', 'Cedar Rapids', 'Cedar Rapids, IA', 'Cedar Rapids, Iowa, United States'),
  ('IA', 'Davenport', 'Davenport, IA', 'Davenport, Iowa, United States'),
  ('KS', 'Wichita', 'Wichita, KS', 'Wichita, Kansas, United States'),
  ('KS', 'Overland Park', 'Overland Park, KS', 'Overland Park, Kansas, United States'),
  ('KS', 'Topeka', 'Topeka, KS', 'Topeka, Kansas, United States'),
  ('KY', 'Louisville', 'Louisville, KY', 'Louisville, Kentucky, United States'),
  ('KY', 'Lexington', 'Lexington, KY', 'Lexington, Kentucky, United States'),
  ('KY', 'Bowling Green', 'Bowling Green, KY', 'Bowling Green, Kentucky, United States'),
  ('LA', 'New Orleans', 'New Orleans, LA', 'New Orleans, Louisiana, United States'),
  ('LA', 'Baton Rouge', 'Baton Rouge, LA', 'Baton Rouge, Louisiana, United States'),
  ('LA', 'Shreveport', 'Shreveport, LA', 'Shreveport, Louisiana, United States'),
  ('ME', 'Portland', 'Portland, ME', 'Portland, Maine, United States'),
  ('ME', 'Lewiston', 'Lewiston, ME', 'Lewiston, Maine, United States'),
  ('ME', 'Bangor', 'Bangor, ME', 'Bangor, Maine, United States'),
  ('MD', 'Baltimore', 'Baltimore, MD', 'Baltimore, Maryland, United States'),
  ('MD', 'Frederick', 'Frederick, MD', 'Frederick, Maryland, United States'),
  ('MD', 'Rockville', 'Rockville, MD', 'Rockville, Maryland, United States'),
  ('MA', 'Boston', 'Boston, MA', 'Boston, Massachusetts, United States'),
  ('MA', 'Worcester', 'Worcester, MA', 'Worcester, Massachusetts, United States'),
  ('MA', 'Springfield', 'Springfield, MA', 'Springfield, Massachusetts, United States'),
  ('MI', 'Detroit', 'Detroit, MI', 'Detroit, Michigan, United States'),
  ('MI', 'Grand Rapids', 'Grand Rapids, MI', 'Grand Rapids, Michigan, United States'),
  ('MI', 'Ann Arbor', 'Ann Arbor, MI', 'Ann Arbor, Michigan, United States'),
  ('MN', 'Minneapolis', 'Minneapolis, MN', 'Minneapolis, Minnesota, United States'),
  ('MN', 'Saint Paul', 'Saint Paul, MN', 'Saint Paul, Minnesota, United States'),
  ('MN', 'Rochester', 'Rochester, MN', 'Rochester, Minnesota, United States'),
  ('MS', 'Jackson', 'Jackson, MS', 'Jackson, Mississippi, United States'),
  ('MS', 'Gulfport', 'Gulfport, MS', 'Gulfport, Mississippi, United States'),
  ('MS', 'Southaven', 'Southaven, MS', 'Southaven, Mississippi, United States'),
  ('MO', 'Kansas City', 'Kansas City, MO', 'Kansas City, Missouri, United States'),
  ('MO', 'St. Louis', 'St. Louis, MO', 'St. Louis, Missouri, United States'),
  ('MO', 'Springfield', 'Springfield, MO', 'Springfield, Missouri, United States'),
  ('MT', 'Billings', 'Billings, MT', 'Billings, Montana, United States'),
  ('MT', 'Missoula', 'Missoula, MT', 'Missoula, Montana, United States'),
  ('MT', 'Bozeman', 'Bozeman, MT', 'Bozeman, Montana, United States'),
  ('NE', 'Omaha', 'Omaha, NE', 'Omaha, Nebraska, United States'),
  ('NE', 'Lincoln', 'Lincoln, NE', 'Lincoln, Nebraska, United States'),
  ('NE', 'Bellevue', 'Bellevue, NE', 'Bellevue, Nebraska, United States'),
  ('NV', 'Las Vegas', 'Las Vegas, NV', 'Las Vegas, Nevada, United States'),
  ('NV', 'Reno', 'Reno, NV', 'Reno, Nevada, United States'),
  ('NV', 'Henderson', 'Henderson, NV', 'Henderson, Nevada, United States'),
  ('NH', 'Manchester', 'Manchester, NH', 'Manchester, New Hampshire, United States'),
  ('NH', 'Nashua', 'Nashua, NH', 'Nashua, New Hampshire, United States'),
  ('NH', 'Concord', 'Concord, NH', 'Concord, New Hampshire, United States'),
  ('NJ', 'Newark', 'Newark, NJ', 'Newark, New Jersey, United States'),
  ('NJ', 'Jersey City', 'Jersey City, NJ', 'Jersey City, New Jersey, United States'),
  ('NJ', 'Paterson', 'Paterson, NJ', 'Paterson, New Jersey, United States'),
  ('NM', 'Albuquerque', 'Albuquerque, NM', 'Albuquerque, New Mexico, United States'),
  ('NM', 'Las Cruces', 'Las Cruces, NM', 'Las Cruces, New Mexico, United States'),
  ('NM', 'Santa Fe', 'Santa Fe, NM', 'Santa Fe, New Mexico, United States'),
  ('NY', 'New York', 'New York, NY', 'New York, New York, United States'),
  ('NY', 'Buffalo', 'Buffalo, NY', 'Buffalo, New York, United States'),
  ('NY', 'Rochester', 'Rochester, NY', 'Rochester, New York, United States'),
  ('NC', 'Charlotte', 'Charlotte, NC', 'Charlotte, North Carolina, United States'),
  ('NC', 'Raleigh', 'Raleigh, NC', 'Raleigh, North Carolina, United States'),
  ('NC', 'Greensboro', 'Greensboro, NC', 'Greensboro, North Carolina, United States'),
  ('ND', 'Fargo', 'Fargo, ND', 'Fargo, North Dakota, United States'),
  ('ND', 'Bismarck', 'Bismarck, ND', 'Bismarck, North Dakota, United States'),
  ('ND', 'Grand Forks', 'Grand Forks, ND', 'Grand Forks, North Dakota, United States'),
  ('OH', 'Columbus', 'Columbus, OH', 'Columbus, Ohio, United States'),
  ('OH', 'Cleveland', 'Cleveland, OH', 'Cleveland, Ohio, United States'),
  ('OH', 'Cincinnati', 'Cincinnati, OH', 'Cincinnati, Ohio, United States'),
  ('OK', 'Oklahoma City', 'Oklahoma City, OK', 'Oklahoma City, Oklahoma, United States'),
  ('OK', 'Tulsa', 'Tulsa, OK', 'Tulsa, Oklahoma, United States'),
  ('OK', 'Norman', 'Norman, OK', 'Norman, Oklahoma, United States'),
  ('OR', 'Portland', 'Portland, OR', 'Portland, Oregon, United States'),
  ('OR', 'Salem', 'Salem, OR', 'Salem, Oregon, United States'),
  ('OR', 'Eugene', 'Eugene, OR', 'Eugene, Oregon, United States'),
  ('PA', 'Philadelphia', 'Philadelphia, PA', 'Philadelphia, Pennsylvania, United States'),
  ('PA', 'Pittsburgh', 'Pittsburgh, PA', 'Pittsburgh, Pennsylvania, United States'),
  ('PA', 'Allentown', 'Allentown, PA', 'Allentown, Pennsylvania, United States'),
  ('RI', 'Providence', 'Providence, RI', 'Providence, Rhode Island, United States'),
  ('RI', 'Warwick', 'Warwick, RI', 'Warwick, Rhode Island, United States'),
  ('RI', 'Cranston', 'Cranston, RI', 'Cranston, Rhode Island, United States'),
  ('SC', 'Charleston', 'Charleston, SC', 'Charleston, South Carolina, United States'),
  ('SC', 'Columbia', 'Columbia, SC', 'Columbia, South Carolina, United States'),
  ('SC', 'Greenville', 'Greenville, SC', 'Greenville, South Carolina, United States'),
  ('SD', 'Sioux Falls', 'Sioux Falls, SD', 'Sioux Falls, South Dakota, United States'),
  ('SD', 'Rapid City', 'Rapid City, SD', 'Rapid City, South Dakota, United States'),
  ('SD', 'Aberdeen', 'Aberdeen, SD', 'Aberdeen, South Dakota, United States'),
  ('TN', 'Nashville', 'Nashville, TN', 'Nashville, Tennessee, United States'),
  ('TN', 'Memphis', 'Memphis, TN', 'Memphis, Tennessee, United States'),
  ('TN', 'Knoxville', 'Knoxville, TN', 'Knoxville, Tennessee, United States'),
  ('TX', 'Houston', 'Houston, TX', 'Houston, Texas, United States'),
  ('TX', 'San Antonio', 'San Antonio, TX', 'San Antonio, Texas, United States'),
  ('TX', 'Dallas', 'Dallas, TX', 'Dallas, Texas, United States'),
  ('UT', 'Salt Lake City', 'Salt Lake City, UT', 'Salt Lake City, Utah, United States'),
  ('UT', 'West Valley City', 'West Valley City, UT', 'West Valley City, Utah, United States'),
  ('UT', 'Provo', 'Provo, UT', 'Provo, Utah, United States'),
  ('VT', 'Burlington', 'Burlington, VT', 'Burlington, Vermont, United States'),
  ('VT', 'South Burlington', 'South Burlington, VT', 'South Burlington, Vermont, United States'),
  ('VT', 'Rutland', 'Rutland, VT', 'Rutland, Vermont, United States'),
  ('VA', 'Virginia Beach', 'Virginia Beach, VA', 'Virginia Beach, Virginia, United States'),
  ('VA', 'Richmond', 'Richmond, VA', 'Richmond, Virginia, United States'),
  ('VA', 'Norfolk', 'Norfolk, VA', 'Norfolk, Virginia, United States'),
  ('WA', 'Seattle', 'Seattle, WA', 'Seattle, Washington, United States'),
  ('WA', 'Spokane', 'Spokane, WA', 'Spokane, Washington, United States'),
  ('WA', 'Tacoma', 'Tacoma, WA', 'Tacoma, Washington, United States'),
  ('WV', 'Charleston', 'Charleston, WV', 'Charleston, West Virginia, United States'),
  ('WV', 'Huntington', 'Huntington, WV', 'Huntington, West Virginia, United States'),
  ('WV', 'Morgantown', 'Morgantown, WV', 'Morgantown, West Virginia, United States'),
  ('WI', 'Milwaukee', 'Milwaukee, WI', 'Milwaukee, Wisconsin, United States'),
  ('WI', 'Madison', 'Madison, WI', 'Madison, Wisconsin, United States'),
  ('WI', 'Green Bay', 'Green Bay, WI', 'Green Bay, Wisconsin, United States'),
  ('WY', 'Cheyenne', 'Cheyenne, WY', 'Cheyenne, Wyoming, United States'),
  ('WY', 'Casper', 'Casper, WY', 'Casper, Wyoming, United States'),
  ('WY', 'Laramie', 'Laramie, WY', 'Laramie, Wyoming, United States')
ON CONFLICT (state_abbr, metro_name) DO NOTHING;
