-- ============================================================================
-- Day 5: Commercial-manufacturer allow-list
-- ----------------------------------------------------------------------------
-- Reason: the OpenFDA-sourced recall_manufacturers table was seeded using the
-- first word of each firm name, producing noise entries like 'Noah', 'Hamilton',
-- 'Depot', 'Family Dollar Stores' that pollute CourtListener case searches.
--
-- This migration:
--   1. Adds is_commercial_manufacturer (default false) so the CL search loop
--      can filter to curated mfrs only.
--   2. Adds cl_search_name: a clean query string used for CL search, derived
--      from the canonical_name with address/country junk stripped.
--   3. Seeds 778 known-good medical-device manufacturers generated from the
--      existing recall_manufacturers contents via Day 5 classification logic
--      (see pipeline/seeds/manufacturer_allow_list.csv).
-- ============================================================================

alter table public.recall_manufacturers
  add column if not exists is_commercial_manufacturer boolean not null default false;

alter table public.recall_manufacturers
  add column if not exists cl_search_name text;

create index if not exists recall_manufacturers_commercial_idx
  on public.recall_manufacturers (is_commercial_manufacturer)
  where is_commercial_manufacturer = true;

-- Apply allow-list via VALUES join
with allow (slug, cl_search_name) as (
  values
('3m','3M'),
('3m-business','3M Business'),
('3m-unitek','3M Unitek'),
('a-l-i-technologies','A L I Technologies'),
('abbott-diabetes-care','Abbott Diabetes Care'),
('abbott-diagnostics-scarborough','Abbott Diagnostics Scarborough'),
('abbott-diagnostics-technologies-as-kjelsasveien','Abbott Diagnostics Technologies As Kjelsasveien'),
('abbott-ireland-finisklin-business-technology-park-sligo-ireland','Abbott'),
('abbott-laboratories','Abbott Laboratories'),
('abbott-laboratories-st-jude','Abbott Laboratories (St Jude )'),
('abbott-max-planck-ring-2-wiesbaden-germany','Abbott Max-Planck-Ring 2 Wiesbaden'),
('abbott-molecular','Abbott Molecular'),
('abbott-point-of-care','Abbott Point Of Care'),
('abbott-vascular','Abbott Vascular'),
('abiomed','Abiomed'),
('accelerate-diagnostics','Accelerate Diagnostics'),
('accelerated-care-plus','Accelerated Care Plus'),
('accriva-diagnostics','Accriva Diagnostics'),
('accuray','Accuray'),
('accure-acne','Accure Acne'),
('ace-surgical-supply','Ace Surgical Supply'),
('actim-oy-klovinpellontie-3-espoo-finland','Actim Oy Klovinpellontie 3 Espoo Finland'),
('activbody','Activbody'),
('acumed','Acumed'),
('adept-2-6-mc-donald-street-morningside-po-box-10075-dominion-rd-auckland-new-zealand','Adept 2-6 Mc Donald Street Morningside Po Box'),
('adler-micromed','Adler Micromed'),
('advance-designs','Advance Designs'),
('advance-dx','Advance Dx'),
('advanced-instruments','Advanced Instruments'),
('advanced-solutions-unit-a-33-road-one-winsford-united-kingdom','Advanced Solutions Unit A 33 Road One Winsford'),
('aesculap','Aesculap'),
('aesculap-implant','Aesculap Implant'),
('agfa','Agfa'),
('agfa-n-v-septestraat-27-mortsel-belgium','Agfa'),
('agilent-technologies','Agilent Technologies'),
('agilent-technologies-denmark-aps-42-produktionsvej-glostrup-denmark','Agilent Technologies'),
('agiliti-ellis','Agiliti Ellis'),
('aizu-olympus-1-chome-1-1-niiderakita-aizuwakamatsu-japan','Olympus'),
('aizu-olympus-3-chome-1-1-niiderakita-aizuwakamatsu-japan','Olympus'),
('aju-pharm-room-201-room-207-bl-a-bundangtekeunopakeu-697-pangyo-ro-bundang-seongnam-korea-the-republic-of','Aju Pharm Room'),
('alcon-research-aspex-facility','Alcon Research Aspex Facility'),
('alcor-scientific','Alcor Scientific'),
('alere-san-diego','Alere San Diego'),
('align-technology','Align Technology'),
('allergan-sales','Allergan Sales'),
('altimate','Altimate'),
('altruan-morolding-6-massing-germany','Altruan Morolding 6 Massing'),
('ambu','Ambu'),
('amd-medicom-2555-ch-de-l-aviation-montreal-canada','Amd Medicom'),
('american-surgical','American Surgical'),
('amo-manufacturing','Amo Manufacturing'),
('amtec-sales','Amtec Sales'),
('andover','Andover'),
('aniara-diagnostica','Aniara Diagnostica'),
('antigua-carretera-sanchez-itabo-haina-dominican-republic-the','Antigua Carretera Sanchez Itabo Haina Dominican Republic (The)'),
('aomori-olympus-2-chome-248-1-okkonoki-kuroishi-japan','Aomori Olympus 2 Chome'),
('apellis-pharmaceuticals','Apellis Pharmaceuticals'),
('apothecary-products','Apothecary Products'),
('applied-resources-22872-avenida-empresa-rancho-santa','Applied Resources'),
('appliedvr','Appliedvr'),
('arcoma-ab-annavagen','Arcoma Ab Annavagen'),
('argon-devices','Argon Devices'),
('arjohuntleigh-magog','Arjohuntleigh Magog'),
('arjohuntleigh-polska-sp-z-o-o-ul-ks-piotra-wawrzyniaka-2-komorniki-poland','Arjohuntleigh'),
('armstrong-services-newbridge-road-wattstown-business-park-coleraine-ireland','Armstrong Services Newbridge Road Wattstown Business'),
('arrow-international','Arrow International'),
('arthrex','Arthrex'),
('artivion','Artivion'),
('ascensia-diabetes-care-us','Ascensia Diabetes Care Us'),
('asp-global-dba-anatomy-supply-partners','Asp Global Dba Anatomy Supply Partners'),
('aspen-surgical','Aspen Surgical'),
('aspen-surgical-products','Aspen Surgical Products'),
('associates-of-cape-cod','Associates Of Cape Cod'),
('athena-products','Athena Products'),
('atricure','Atricure'),
('atrium','Atrium'),
('augmedics-2-ha-otsma-st-yokneam-illit-northern-israel','Augmedics 2 Ha-Otsma'),
('augustine-temperature-management','Augustine Temperature Management'),
('b-braun','B Braun'),
('b-braun-s-celsa-lg-30-avenue-des-temps-modernes-cs-10031-chasseneuil-du-poitou-cedex-france','B Braun S Celsa Lg 30 Avenue Des Temps Modernes; Cs'),
('barco-n-v-president-kennedypark-35-kortrijk-belgium','Barco'),
('bard-access','Bard Access'),
('bard-peripheral-vascular','Bard Peripheral Vascular'),
('bard-peripheral-vascular-1625-w-3rd-st-bldg-1-850-w-rio-salado-prkwy-tempe-az-85281-2438','Bard Peripheral Vascular'),
('base-10-genetics','Base 10 Genetics'),
('bd-kiestra-lab-automation-marconilaan-6-drachten-netherlands','Bd Kiestra Lab Automation Marconilaan 6 Drachten'),
('bearcare','Bearcare'),
('bebig-isotopentechnik-robert-rossle-str-10-berlin-germany','Bebig Isotopentechnik Robert-Rossle-Str 10 Berlin'),
('beckman-coulter-biomedical-division-lismeehan-o-callaghan-s-mills-county-clare-ireland','Beckman Coulter'),
('beckman-coulter-biomedical-sauerbruchstr-50-munchen-germany','Beckman Coulter'),
('beckman-coulter-ireland-lismeehan-o-callaghan-s-mills-ireland','Beckman Coulter'),
('beckman-coulter-laboratory-suzhou-no','Beckman Coulter Laboratory (Suzhou) No'),
('beckman-coulter-mishima-k-k-454-32-higashino-nagaizumi-cho-sunto-gun-japan','Beckman Coulter'),
('beeken-biomedical','Beeken Biomedical'),
('berkeley-advanced-biomaterials','Berkeley Advanced Biomaterials'),
('beta-bionics','Beta Bionics'),
('bigfoot-biomedical','Bigfoot Biomedical'),
('binx-245-1st-st-ste-18-riverview-ii-cambridge-ma-02142-1292','Binx'),
('bio-rad-laboratories','Bio-Rad Laboratories'),
('biocare','Biocare'),
('biocartis-b-3-generaal-de-wittelaan-11-mechelen-belgium','Biocartis B 3 Generaal De Wittelaan 11 Mechelen'),
('biofire-diagnostics','Biofire Diagnostics'),
('biointellisense-570-el-camino-real','Biointellisense'),
('biokit-avinguda-de-can-montcau-7-barcelona-llica-d-amunt-spain','Biokit Avinguda De Can Montcau 7 (Barcelona) Llica D''Amunt Spain'),
('biomerieux','Biomerieux'),
('biosense-webster','Biosense Webster'),
('bolder-surgical','Bolder Surgical'),
('boston-foundation-for-sight','Boston Foundation For Sight'),
('boston-scientific','Boston Scientific'),
('braemar-manufacturing','Braemar Manufacturing'),
('brahms-neuendorfstr-25-hennigsdorf-germany','Brahms Neuendorfstr 25 Hennigsdorf'),
('brainlab-olof-palme-str-9-munich-germany','Brainlab'),
('brasseler','Brasseler'),
('brasseler-i-lp','Brasseler I Lp'),
('breas','Breas'),
('bridge-to-life','Bridge To Life'),
('brius-technologies','Brius Technologies'),
('btt-billerberg-7-inning-germany','Btt Billerberg 7 Inning'),
('busse-hospital-disposables','Busse Hospital Disposables'),
('c-r-bard','C R Bard'),
('c-rad-positioning-ab-bredgrand-18-uppsala-sweden','C-Rad'),
('cadwell-industries','Cadwell Industries'),
('caire','Caire'),
('caption','Caption'),
('cardiac-assist','Cardiac Assist'),
('cardinal','Cardinal Health'),
('cardiotek-amerikalaan-70-maastricht-airport-netherlands','Cardiotek Amerikalaan 70 Maastricht-Airport'),
('carefree-surgical-specialties','Carefree Surgical Specialties'),
('carefusion','Carefusion'),
('carestream','Carestream'),
('carl-zeiss-meditec','Carl Zeiss Meditec'),
('carl-zeiss-meditec-rudolf-eber-str-11-oberkochen-germany','Carl Zeiss Meditec Rudolf-Eber-Str 11 Oberkochen'),
('cell-marque','Cell Marque'),
('cellavision-ab-forskningsbyn-ideon-scheelevagen-19a-lund-sweden','Cellavision Ab Forskningsbyn Ideon Scheelevagen 19A Lund'),
('centerline-biomedical','Centerline Biomedical'),
('cerenovus','Cerenovus'),
('chamberlain-technologies','Chamberlain Technologies'),
('changchun-wancheng-bio-electron-2336-tianwei-road-beihu-science-and-technology-development-zone-changchun-china','Changchun Wancheng Bio-Electron'),
('changzhou-biomet-devices-no-235-longhutangjieban-chuangxindadao-xinbei-changzhou-china','Changzhou Biomet Devices No'),
('checkpoint-surgical','Checkpoint Surgical'),
('chromsystems-instruments-chemicals-am-haag-12-grafelfing-germany','Chromsystems Instruments & Chemicals Am Haag 12 Grafelfing'),
('church-dwight','Church & Dwight'),
('circulatory-technology','Circulatory Technology'),
('civco-instruments','Civco Instruments'),
('clariance-sas-18-rue-robespierre-beaurains-france','Clariance-Sas 18 Rue Robespierre Beaurains'),
('clark-laboratories','Clark Laboratories'),
('clinician-s-choice-dental-products','Clinician''S Choice Dental Products'),
('collagen-matrix','Collagen Matrix'),
('coloplast-manufacturing-us','Coloplast Manufacturing Us'),
('coltene-whaledent','Coltene Whaledent'),
('community-products','Community Products'),
('compass-brands-corporate-office','Compass Brands (Corporate Office)'),
('conformis','Conformis'),
('contec-economic-and-no','Contec Economic And No'),
('contract-international-lauensteiner-str-37-dresden-germany','Contract International Lauensteiner'),
('convergent-dental','Convergent Dental'),
('cook-biotech','Cook Biotech'),
('cook-vandergrift','Cook Vandergrift'),
('coopervision','Coopervision'),
('copan-diagnostics','Copan Diagnostics'),
('copan-italia-via-francesco-perotti-10','Copan'),
('copan-italia-via-francesco-perotti-10-brescia-italy','Copan'),
('copan-wasp-via-achille-grandi','Copan Wasp Via Achille Grandi'),
('cordis-us','Cordis Us'),
('corelink','Corelink'),
('corentec-12-yeongsanhong1-gil-seobuk-cheonan-korea-the-republic-of','Corentec 12 Yeongsanhong1-Gil; Seobuk Cheonan Korea (The Republic Of)'),
('cpm-consultants','Cpm Consultants'),
('creganna-devices-parkmore-house-mweeloon-galway-ireland','Creganna Devices Parkmore House Mweeloon Galway'),
('cypress-products','Cypress Medical'),
('cytocell-418-cambridge-science-park-milton-road-oxford-gene-technology-cambridge-united-kingdom','Cytocell'),
('cytrellis-biosystems','Cytrellis Biosystems'),
('d-o-r-c-dutch-opthalmic-research-center-intl-b-v-scheijdelveweg-2-zuidland-netherlands','D O R C Dutch Opthalmic Research Center Intl B V Scheijdelveweg 2 Zuidland'),
('daavlin-distributing','Daavlin Distributing'),
('dain-technology-subsidiary-of-soundable-seocho-daero-seocho-413-398-platinum-tower-seoul-korea-the-republic-of','Dain Technology (Subsidiary Of Soundable ) Seocho-Daero Seocho #'),
('davol','Davol'),
('daye-anne-s-day-biscuit-factory-business-complex-100-drummond-road-london-united-kingdom','Daye (Anne''S Day ) Biscuit Factory Business Complex'),
('dds-lab','Dds Lab'),
('defibtech','Defibtech'),
('delta-med-spa-via-guido-rossa-20-viadana-italy','Delta Med Spa Via Guido Rossa 20 Viadana Italy'),
('dental-choice-holding','Dental Choice Holding'),
('dental-ez-star-dental-division','Dental Ez Star Dental Division'),
('dentsply-ih','Dentsply Ih'),
('depuy-ireland-uc-loughbeg-ringaskiddy-cork-munster-ireland','Depuy'),
('depuy-mitek-a-johnson-johnson','Depuy Mitek A Johnson & Johnson'),
('depuy-spine','Depuy Spine'),
('dermasensor','Dermasensor'),
('dermlite','Dermlite'),
('deroyal-industries-lafollette','Deroyal Industries Lafollette'),
('devicor-products','Devicor Products'),
('devilbiss','Devilbiss'),
('dexcom','Dexcom'),
('diagnos','Diagnos'),
('diasorin','Diasorin'),
('diasorin-molecular','Diasorin Molecular'),
('dicom-grid','Dicom Grid'),
('dicom-grid-d-b-a-ambra','Dicom Grid D/B/A Ambra'),
('digimed-401-402-406-411-ho-a-dong-101-gasan-digital-2-ro-geumcheon-gu-seoul-korea-the-republic-of','Digimed'),
('digisonics','Digisonics'),
('dignitana','Dignitana'),
('diversatek','Diversatek'),
('djo','Djo'),
('dna-genotek-3000-500-palladium-dr-kanata-canada','Dna Genotek'),
('dr-franz-koehler-chemie-werner-von-siemens-str-14-28-bensheim-germany','Dr Franz Koehler Chemie Werner-Von-Siemens-Str 14-28 Bensheim'),
('draegar','Draegar'),
('draegerwerk-kgaa-dragerwerk-kgaa-accounts-payable-moislinger-allee','Draegerwerk & Kgaa Dragerwerk & Kgaa Accounts Payable Moislinger Allee'),
('drg-international','Drg International'),
('drs-vascular','Drs Vascular'),
('dynasthetics','Dynasthetics'),
('dynex-technologies','Dynex Technologies'),
('echonous','Echonous'),
('edan-diagnostics','Edan Diagnostics'),
('edge-biologicals','Edge Biologicals'),
('eight-international-laan-van-hildernisse-noord-2a-bergen-op-zoom-netherlands','Eight International Laan Van Hildernisse-Noord 2A Bergen Op Zoom'),
('electro-chemin-de-la-vuarpilliere','Electro Chemin De La Vuarpilliere'),
('elekta-instrument-ab-kungstensgatan-18-stockholm-sweden','Elekta'),
('elucent','Elucent'),
('embecta','Embecta'),
('emd-millipore','Emd Millipore'),
('emergency-products-research','Emergency Products & Research'),
('emergent-protective-products','Emergent Protective Products'),
('enchroma','Enchroma'),
('endo-pharmaceuticals-solutions','Endo Pharmaceuticals Solutions'),
('endo-therapeutics','Endo-Therapeutics'),
('endomagnetics-st-johns-innovation-park-cowley-road-cambridge-united-kingdom','Endomagnetics'),
('enterix','Enterix'),
('entopsis','Entopsis'),
('envisiontec-us','Envisiontec Us'),
('esaote-s-p-a-sesto-fiorentino-via-degli-olmi-11-sesto-fiorentino-italy','Esaote S P A Sesto Fiorentino Via Degli Olmi 11 Sesto Fiorentino Italy'),
('etac-a-s-parallelvej-3-gedved-denmark','Etac A/S Parallelvej 3 Gedved'),
('ethicon','Ethicon'),
('ethicon-calle-durango-2751-col-parque-industrial-juarez-juarez-mexico','Ethicon Calle Durango'),
('exact-manufacturing','Exact Manufacturing'),
('exocad-julius-reiber-str-37-darmstadt-germany','Exocad Julius-Reiber-Str 37 Darmstadt'),
('eye-comfort-care','Eye Comfort Care'),
('femselect-hama-ayan-2-first-floor-modi-in-israel','Femselect Hama''Ayan 2 First Floor Modi''In'),
('feng-chun-yuan-equipment-shenzhen-no-1304-science-and-technology-innovation-park-shajing-dahong-shenzhen-china','Feng Chun Yuan Equipment (Shenzhen) No'),
('ferndale-laboratories','Ferndale Laboratories'),
('first-source','First Source'),
('fisher-diagnostics','Fisher Diagnostics'),
('fisher-wallace-laboratories','Fisher Wallace Laboratories'),
('flexdex','Flexdex'),
('flexicare-dongguan-hengli-town-no-b-15-xicheng-henglizhen-dongguan-china','Flexicare (Dongguan) Hengli Town No B-15 Xicheng; Henglizhen Dongguan'),
('flosonics-r-a-1929803-ontario-fourth-floor-oneeleven-325-front-st-w-toronto-canada','Flosonics (R/A'),
('focalyx-technologies','Focalyx Technologies'),
('folsom-metal-products','Folsom Metal Products'),
('forbes-rehab-services','Forbes Rehab Services'),
('fresenius-care','Fresenius Care'),
('fresenius-kabi','Fresenius Kabi'),
('freudenberg','Freudenberg'),
('fujifilm-irvine-scientific','Fujifilm Irvine Scientific'),
('fujirebio-diagnostics','Fujirebio Diagnostics'),
('future-diagnostics-solutions-b-v-nieuweweg-279-wijchen-netherlands','Future Diagnostics Solutions B V Nieuweweg'),
('fx-shoulder','Fx Shoulder'),
('g-h-wire','G & H Wire'),
('gauthier-biomedical','Gauthier Biomedical'),
('ge','Ge'),
('ge-austria-tiefenbach-15-pfaffing-austria','Ge Austria & Tiefenbach 15 Pfaffing Austria'),
('ge-china-1f-5f-bld-1-no-1-tongji-south-road-beijing-economic-technological-development-area-beijing-china','GE Healthcare'),
('ge-china-dev-zone-national-hi-tech-no','GE Healthcare'),
('ge-china-national-hi-tech-no','GE Healthcare'),
('ge-finland-oy-kuortaneenkatu-2-helsinki-finland','Ge Finland Oy Kuortaneenkatu 2 Helsinki Finland'),
('ge-hangwei-west-area-bldg-3-no-1-yongchang-north-road-1-yongchangbeilu-beijing-economic-and-technological-development-area-beijing-china','GE Healthcare'),
('ge-information-technologies','Ge Information Technologies'),
('ge-israel-functional-imaging-4-hayozma-st-tirat-carmel-israel','GE Healthcare'),
('ge-israel-functional-imaging-9-andrey-sakharov-haifa-israel','GE Healthcare'),
('ge-israel-nativ-haa-or-street-no','GE Healthcare'),
('ge-oec','Ge Oec'),
('ge-oskar-schlemmer-str-11-munich-germany','GE Healthcare'),
('ge-vingmed-ultrasound-as-strandpromenaden-45-horten-norway','GE Healthcare'),
('gelita-uferstr-7-eberbach-germany','Gelita Uferstr 7 Eberbach'),
('gentherm','Gentherm'),
('gentuity','Gentuity'),
('get-tested-international-ab-59334-vastervik-lysingsvagen-18-vastervik-sweden','Get Tested International Ab'),
('gibson-bioscience','Gibson Bioscience'),
('given-imaging-new-industrial-park','Given Imaging New Industrial Park'),
('globus','Globus'),
('gold-star-distribution','Gold Star Distribution'),
('gramercy-extremity-orthopedics','Gramercy Extremity Orthopedics'),
('graphenano-dental-sl-calle-de-pau-casals','Graphenano Dental Sl Calle De Pau Casals'),
('graphic-controls-acquisition','Graphic Controls Acquisition'),
('greer-laboratories','Greer Laboratories'),
('greiner-bio-one','Greiner Bio-One'),
('greiner-bio-one-bad-haller-strase','Greiner Bio-One Bad Haller Strase'),
('guangdong-haiou-apparatus-nanyuan-industrial-zone-north-liusha-puning-china','Guangdong Haiou Apparatus Nanyuan Industrial Zone North Liusha Puning'),
('gvs-tm','Gvs Tm'),
('haag-streit','Haag-Streit'),
('haemonetics','Haemonetics'),
('haimen-shengbang-laboratory-equipment-d-sanhe-no-50-xue-qian-road-sanhezhen-haimen-nantong-china','Haimen Shengbang Laboratory Equipment D Sanhe No 50 Xue Qian Road; Sanhezhen Haimen Nantong'),
('hamamatsu','Hamamatsu'),
('hamilton-parc-industrial-vial-10-domat-ems-switzerland','Hamilton'),
('hamilton-via-crusch-8-bonaduz-switzerland','Hamilton'),
('hangzhou-acosound-technology-no-2-building-room-401-no','Hangzhou Acosound Technology No 2 Building Room'),
('hangzhou-bever-devices','Hangzhou Bever Devices'),
('hardy-diagnostics','Hardy Diagnostics'),
('healgen-scientific','Healgen Scientific'),
('healthmark-industries','Healthmark Industries'),
('helena-laboratories','Helena Laboratories'),
('hemocue-ab-kuvettgatan-1-angelholm-sweden','Hemocue Ab Kuvettgatan 1 Angelholm'),
('heraeus-dental-division-philipp-reis-str-8-wehrheim-germany','Heraeus (Dental Division) Philipp-Reis-Str 8 Wehrheim'),
('hermes-solutions-ab-strandbergsgatan-16-stockholm-sweden','Hermes Solutions Ab Strandbergsgatan 16 Stockholm'),
('hf-acquisition','Hf Acquisition'),
('hill-rom','Hill-Rom'),
('hiossen','Hiossen'),
('hiossen-keystone-industrial-port-complex','Hiossen Keystone Industrial Port Complex'),
('hitachi','Hitachi'),
('hitachi-america-particle-therapy-division','Hitachi America Particle Therapy Division'),
('hitachi-radiation-oncology-kashiwanoha-44-141-1-w-226-wakashiba-kashiwa-japan','Hitachi Radiation Oncology Kashiwanoha 44-'),
('hollister','Hollister'),
('hologic','Hologic'),
('home-us','Home Us'),
('human-care','Human Care'),
('human-care-hc-sweden-ab-arstaangsvagen-21-b-stockholm-sweden','Human Care Hc'),
('human-med-wilhelm-hennemann-str-9-schwerin-germany','Human Med Wilhelm-Hennemann-Str 9 Schwerin'),
('huntleigh','Huntleigh'),
('i-t-s-autal-28-lasnitzhohe-austria','I T S Autal 28 Lasnitzhohe Austria'),
('iba-dosimetry-bahnhofstr-5-schwarzenbruck-germany','Iba Dosimetry Bahnhofstr 5 Schwarzenbruck'),
('icotec-industriestrasse-12-altstatten-sg-switzerland','Icotec'),
('ihb-operations-b-v-floresstraat-52-zwolle-netherlands','IHB Operations'),
('illumina','Illumina'),
('immundiagnostik','Immundiagnostik'),
('immunostics','Immunostics'),
('immunotech-a-s-radiova-1-prague','Immunotech A S Radiova 1 Prague'),
('imperative-care','Imperative Care'),
('implantcast-luneburger-schanze-26-buxtehude-germany','Implantcast Luneburger Schanze 26 Buxtehude'),
('imris-imaging','Imris Imaging'),
('in2bones','In2Bones'),
('in2bones-sas-28-chemin-du-petit-bois-ecully-france','In2Bones Sas 28 Chemin Du Petit Bois Ecully'),
('incipio-devices-avenue-des-paquiers-16-st-blaise-switzerland','Incipio Devices Avenue Des Paquiers 16'),
('infutronix','Infutronix'),
('innomed','Innomed'),
('innovasis','Innovasis'),
('insightra','Insightra'),
('institut-georges-lopez-6-route-de-saint-bonnet-st-laurent-de-chamousset-france','Institut Georges Lopez 6 Route De Saint Bonnet'),
('integra-lifesciences','Integra Lifesciences'),
('integra-lifesciences-neurosciences','Integra Lifesciences (Neurosciences)'),
('integrity-implants','Integrity Implants'),
('intelerad-800-boul-de-maisonneuve-est-12th-floor-montreal-canada','Intelerad'),
('international-life-sciences','International Life Sciences'),
('international-science-technology-lp-dba-diamatrix','International Science & Technology Lp Dba Diamatrix'),
('intrinsic-therapeutics','Intrinsic Therapeutics'),
('invacare','Invacare'),
('ion-beam-applications-3-chemin-du-cyclotron-louvain-la-neuve-belgium','Ion Beam Applications'),
('ion-beam-applications-chemin-du-cyclotron-3-louvain-la-neuve-belgium','Ion Beam Applications'),
('ion-beam-applications-chemin-du-cyclotron-3-ottignies-louvain-la-neuve-belgium','Ion Beam Applications'),
('iotamotion','Iotamotion'),
('iradimed','Iradimed'),
('isotis-orthobiologics','Isotis Orthobiologics'),
('ivoclar-vivadent','Ivoclar Vivadent'),
('ivoclar-vivadent-bedersrasse-liechtstein-germany','Ivoclar Vivadent Bedersrasse Liechtstein'),
('j-t-and-wellness','J & T And Wellness'),
('jewel-precision-sheet-metal-machining','Jewel Precision Sheet Metal & Machining'),
('jiangsu-jumao-x-care-equipment-no','Jiangsu Jumao X-Care Equipment No'),
('jiangsu-shenli-production-no','Jiangsu Shenli Production No'),
('johnson-johnson-vision-care','Johnson & Johnson Vision Care'),
('jolife-ab-scheelevagen-17-ideon-science-park-lund-sweden','Jolife Ab Scheelevagen 17 Ideon Science'),
('kamiya-biomedical','Kamiya Biomedical'),
('kent-imaging','Kent Imaging'),
('ki-mobility','Ki Mobility'),
('king-dba-ambu','King Dba Ambu'),
('kirwan-surgical-products','Kirwan Surgical Products'),
('klinika-mdical-gmb-achtzehnmorgenweg-6-usingen-germany','Klinika Mdical Gmb Achtzehnmorgenweg 6 Usingen'),
('kob-lauterstr-50-wolfstein-germany','Kob Lauterstr 50 Wolfstein'),
('konica-minolta','Konica Minolta'),
('koven-technology','Koven Technology'),
('kreatech-biotechnology-vlierweg-20-amsterdam-netherlands','Kreatech Biotechnology Vlierweg 20 Amsterdam'),
('kung-shin-plastics-65-2-erh-chia-road-ying-kuo-town-taipei-hsien-taiwan','Kung Shin Plastics 65-2 Erh Chia Road Ying Kuo Town Taipei Hsien Taiwan'),
('laboratoires-bodycad','Laboratoires Bodycad'),
('labories-technologies','Labories Technologies'),
('laerdal','Laerdal'),
('leaseir-technologies-slu-calle-marconi-g-246-gijon-spain','Leaseir Technologies Slu Calle Marconi G'),
('leica-biosystems-melbourne','Leica Biosystems Melbourne'),
('leica-microsystems','Leica Microsystems'),
('lemaitre-vascular','Lemaitre Vascular'),
('leoni-cia-cable-5-avenue-victor-hugo-chartres-france','Leoni Cia Cable 5 Avenue Victor Hugo Chartres'),
('letsgetchecked','Letsgetchecked'),
('liberty-solutions','Liberty Solutions'),
('life-technologies','Life Technologies'),
('limflow','Limflow'),
('lineage-biomedical','Lineage Biomedical'),
('linet-spol-s-r-o-zelevcice-5-zelevcice-czech-republic','Linet Spol S R O Zelevcice 5 Zelevcice Czech Republic'),
('link-bio','Link Bio'),
('linkbio','Linkbio'),
('lts-therapy','Lts Therapy'),
('lucid-diagnostics','Lucid Diagnostics'),
('lumenis-yokneam-ind-park-6-ha-kidma-yokne-am-ilit-israel','Lumenis'),
('luminex','Luminex'),
('lumiradx','Lumiradx'),
('lumithera','Lumithera'),
('m-d-l-s-r-l-via-tavani-n-1-a-delebio-italy','M D L S R L Via Tavani N 1/A Delebio Italy'),
('mac-supply','Mac Supply'),
('macherey-nagel-kg-valencienner-str-11-duren-germany','Macherey Nagel & Kg Valencienner'),
('mako-surgical','Mako Surgical'),
('mallinckrodt','Mallinckrodt'),
('mallinckrodt-manufacturing','Mallinckrodt Manufacturing'),
('mani-kiyohara-facility-park-8-3-kiyoharakogyodanchi-kiyoharakogyodanchi-kiyoharakogyodanchi-utsunomiya-japan','Mani Kiyohara'),
('maquet','Maquet'),
('maquet-cardiopulmonary-kehler-str-31-rastatt-germany','Maquet'),
('maquet-critical-care-ab-rontgenvagen','Maquet Critical Care Ab Rontgenvagen'),
('maquet-kehler-str-31-rastatt-germany','Maquet'),
('masimo','Masimo'),
('materialise','Materialise'),
('materialise-n-v-technologielaan-15-heverlee-belgium','Materialise'),
('max-mobility','Max Mobility'),
('mechatronics','Mechatronics'),
('med-michigan-holding','Med Michigan Holding'),
('med-mizer','Med-Mizer'),
('medacta','Medacta'),
('medagent','Medagent'),
('medartis','Medartis'),
('medartis-hochbergerstrasse-60e-basel-town-switzerland','Medartis Hochbergerstrasse 60E Basel Town'),
('mediana-132-donghwagongdan-ro-munmag-eup-wonju-korea-the-republic-of','Mediana'),
('medicalcommunications-max-jarecki-str-8-heidelberg-germany','Medicalcommunications Max-Jarecki-Str 8 Heidelberg'),
('medicalplastic-s-r-l-via-saverio-mercadante','Medicalplastic S R L Via Saverio Mercadante'),
('medicrea-international-vancia-vancia-rillieux-la-pape-france','Medicrea International Vancia Vancia Rillieux La Pape'),
('medimaps-fongit-chemin-des-aulx-18-plan-les-ouates-switzerland','Medimaps Fongit Chemin Des Aulx 18 Plan-Les-Ouates'),
('medistim-asa-okernveien','Medistim Asa Okernveien'),
('medivance','Medivance'),
('medline-industries','Medline Industries'),
('medline-industries-12001-general-milton','Medline Industries'),
('medline-industries-lp-spt','Medline Industries Lp Spt'),
('medminder','Medminder'),
('medos-international-sarl-chemin-blanc-36-le-locle-switzerland','Medos International Sarl Chemin Blanc 36 Le Locle'),
('medshape','Medshape'),
('medtronic','Medtronic'),
('medtronic-formerly-covidien-michael-collins-road-mervue-ind-park-galway-ireland','Medtronic'),
('medtronic-minimed','Medtronic Minimed'),
('medtronic-navigation-boxborough','Medtronic Navigation -Boxborough'),
('medtronic-navigation-littleton','Medtronic Navigation -Littleton'),
('medtronic-neuromodulation','Medtronic Neuromodulation'),
('medtronic-neurosurgery','Medtronic Neurosurgery'),
('medtronic-perfusion','Medtronic Perfusion'),
('medtronic-vascular','Medtronic Vascular'),
('megadyne-products','Megadyne Products'),
('menarini-silicon-biosystems','Menarini Silicon Biosystems'),
('mercury-enterprises-dba-mercury','Mercury Enterprises Dba Mercury'),
('merete-alt-lankwitz-102-berlin-germany','Merete Alt-Lankwitz'),
('merge','Merge Healthcare'),
('meridian-bioscience','Meridian Bioscience'),
('mermaid-a-s-frydensbergvej-25-stenlose-denmark','Mermaid A/S Frydensbergvej 25 Stenlose'),
('meta-c-g-m-spa-via-modena-22-24-correggio-italy','Meta C G M Spa Via Modena 22-24 Correggio Italy'),
('miach-orthopaedics','Miach Orthopaedics'),
('micro-therapeutics','Micro Therapeutics'),
('micro-x-a14-6-mab-eastern-promenade-tonsley-australia','Micro-X'),
('micro-x-unit-14-6-mab-eastern-promenade-tonsley-australia','Micro-X'),
('microaire-surgical-instruments','Microaire Surgical Instruments'),
('microbiologics','Microbiologics'),
('microcare','Microcare'),
('microgenics','Microgenics'),
('microline-surgical','Microline Surgical'),
('microport-orthopedics','Microport Orthopedics'),
('microspecialties','Microspecialties'),
('microsurgical-technology','Microsurgical Technology'),
('microtek','Microtek'),
('mim-software','Mim Software'),
('mindray-ds-dba-mindray','Mindray Ds Dba Mindray'),
('mint-friedrich-ebert-str-2-dossenheim-germany','Mint Friedrich-Ebert-Str 2 Dossenheim'),
('mirion-technologies-capintec','Mirion Technologies (Capintec)'),
('mivi-neuroscience','Mivi Neuroscience'),
('mizuho-osi','Mizuho Osi'),
('mo-vis-bvba-biebuyckstraat-15d-nevele-belgium','Mo-Vis Bvba Biebuyckstraat 15D Nevele'),
('moberg-research','Moberg Research'),
('mobius-imaging','Mobius Imaging'),
('mobius-mobility','Mobius Mobility'),
('modeling','Modeling'),
('molded-products','Molded Products'),
('moximed','Moximed'),
('mozarc-us','Mozarc Us'),
('mrp-dba-aquabiliti','Mrp Dba Aquabiliti'),
('murata-vios','Murata Vios'),
('musculoskeletal-transplant-foundation','Musculoskeletal Transplant Foundation'),
('myofunctional-research','Myofunctional Research'),
('natus','Natus'),
('natus-neurology','Natus Neurology'),
('natus-neurology-dba-excel-tech-xltek','Natus Neurology Dba Excel Tech (Xltek)'),
('navajo-manufacturing','Navajo Manufacturing'),
('navinetics','Navinetics'),
('neilmed-pharmaceuticals','Neilmed Pharmaceuticals'),
('neotract','Neotract'),
('neumodx-molecular','Neumodx Molecular'),
('neuralynx','Neuralynx'),
('neurologica','Neurologica'),
('neurosync','Neurosync'),
('neurovision-products','Neurovision Products'),
('new-technologies-wankdorffeldstrasse','New Technologies Wankdorffeldstrasse'),
('nextremity-solutions','Nextremity Solutions'),
('nihon-kohden-america','Nihon Kohden America'),
('nihon-kohden-orangemed','Nihon Kohden Orangemed'),
('nikkiso-shizuoka-plant-498-1-shizutani-shizuoka-ken-makinohara-japan','Nikkiso Shizuoka Plant'),
('nipro-renal-soultions','Nipro Renal Soultions'),
('nipro-technical-services','Nipro Technical Services'),
('noa-industries','Noa Industries'),
('nobel-biocare','Nobel Biocare'),
('nobel-biocare-vastra-hamngatan-1-goteborg-sweden','Nobel Biocare Vastra Hamngatan 1 Goteborg'),
('nordicneurolab-as-mollendalsveien-65c-bergen-norway','Nordicneurolab As Mollendalsveien 65C Bergen'),
('north-american-rescue','North American Rescue'),
('northgate-technologies','Northgate Technologies'),
('novapproach-spine','Novapproach Spine'),
('novasignal','Novasignal'),
('novosource','Novosource'),
('nrt-x-ray-a-s-birkegardsvej-16-birkegaardsvej-16-hasselager-denmark','Nrt X-Ray A/S Birkegardsvej 16 Birkegaardsvej 16 Hasselager'),
('nrt-x-ray-a-s-birkegardsvej-16-hasselager-denmark','Nrt X-Ray A/S Birkegardsvej 16 Hasselager'),
('nuclein','Nuclein'),
('nurse-assist','Nurse Assist'),
('nuvasive','Nuvasive'),
('nuvasive-specialized-orthopedics','Nuvasive Specialized Orthopedics'),
('nuwellis','Nuwellis'),
('nxstage','Nxstage'),
('nxstage-mds','Nxstage Mds'),
('o-m-halyard','O & M Halyard'),
('oakworks','Oakworks'),
('oculus-optikgeraete-munchholzhauser-str-29-wetzlar-germany','Oculus Optikgeraete Munchholzhauser'),
('omm-imports-dba-zero-gravity','Omm Imports Dba Zero Gravity'),
('omnicell','Omnicell'),
('omnilife-science','Omnilife Science'),
('onkos-surgical','Onkos Surgical'),
('ontact-10944-playa-del-sol','Ontact'),
('optumhealth-care-solutions','Optumhealth Care Solutions'),
('orascoptic-surgical-acuity','Orascoptic Surgical Acuity'),
('orchestrate-orthodontic-technologies','Orchestrate Orthodontic Technologies'),
('oridion-1987-har-hotzvim-industrial','Oridion'),
('origen-biomedical','Origen Biomedical'),
('orthalign','Orthalign'),
('ortho-clinical-diagnostics','Ortho-Clinical Diagnostics'),
('ortho-clinical-diagnostics-felindre-meadows-bridgend-united-kingdom','Ortho-Clinical Diagnostics'),
('orthofix-srl-via-delle-nazioni-9-bussolengo-italy','Orthofix Srl Via Delle Nazioni 9 Bussolengo Italy'),
('orthofix-u-s','Orthofix U S'),
('orthopediatrics','Orthopediatrics'),
('orthopediatrics-canada-ulc-dba-pega-1111-chomedey-a-13-e-laval-canada','Orthopediatrics'),
('orthoscan','Orthoscan'),
('orthosoft-dba-zimmer-cas-3300-75-queen-st-montreal-canada','Orthosoft Dba Zimmer Cas'),
('ortoma-ab-falkenbergsgatan-3-goteborg-sweden','Ortoma Ab Falkenbergsgatan 3 Goteborg'),
('osstem-implant-66-16-bansong-ro-513beon-gil-busan-city-haeundae-district-korea-the-republic-of','Osstem Implant 66-16 Bansong-Ro 513Beon-Gil Busan City Haeundae District Korea (The Republic Of)'),
('ossur','Ossur'),
('osteomed','Osteomed'),
('osteotec','Osteotec'),
('owen-mumford','Owen Mumford'),
('owens-minor-distribution','Owens & Minor Distribution'),
('oxoid-australia-20-dlgleish-st-south-australia-australia','Oxoid'),
('oxoid-wade-road-basingstoke-united-kingdom','Oxoid Wade Road Basingstoke'),
('pajunk-l-p','Pajunk L P'),
('palodex-oy-nahkelantie-160-tuusula-finland','Palodex Oy Nahkelantie'),
('paragon-28-14445-grasslands-dr-englewood-80112-7062','Paragon 28'),
('parker-laboratories','Parker Laboratories'),
('path-landsberger-str-65-germering-germany','Path Landsberger'),
('pear-therapeutics','Pear Therapeutics'),
('penner-patient-care','Penner Patient Care'),
('pentax-of-america','Pentax Of America'),
('permobil','Permobil'),
('peter-lazic-immelmannweg-2-tuttlingen-germany','Peter Lazic Immelmannweg 2 Tuttlingen'),
('phadia-ab-rapsgatan-plant-rapsgatan-7-uppsala-sweden','Phadia Ab Rapsgatan Plant Rapsgatan 7 Uppsala'),
('phadia-us','Phadia Us'),
('philips','Philips'),
('philips-cleveland','Philips (Cleveland)'),
('philips-dmc-development-and-manufacturing-ctr-rontgenstr-24-26-hamburg-germany','Philips'),
('philips-dmc-development-and-manufacturing-ctr-rontgenstr-24-hamburg-germany','Philips'),
('philips-headquarters-cambridge','Philips Headquarters Cambridge'),
('philips-nederland-b-v-high-tech-campus-36-eindhoven-netherlands','Philips'),
('philips-nederland-b-v-veenpluis','Philips Nederland B V Veenpluis'),
('philips-respironics','Philips Respironics'),
('philips-suzhou-suzhou-industrial-park-no','Philips (Suzhou) Suzhou Industrial Park No'),
('philips-technologies-matam-building-8-2-advanced-technology-center-haifa-israel','Philips'),
('pie-imaging-b-v-demertdwarsstraat-8a01-maastricht-netherlands','Pie Imaging B V Demertdwarsstraat 8A01 Maastricht'),
('pivotal-solutions','Pivotal Solutions'),
('polymedco-polymedco-cancer-diagnostic-products','Polymedco Polymedco Cancer Diagnostic Products'),
('premier-dental-products','Premier Dental Products'),
('primus-dba-trinity-biotech','Primus Dba Trinity Biotech'),
('princeton-biomeditech','Princeton Biomeditech'),
('prismatik-dentalcraft','Prismatik Dentalcraft'),
('pro-dex','Pro-Dex'),
('pro-med-instruments-boetzinger-strasse-86-freiburg-im-breisgau-germany','Pro-Med Instruments Boetzinger'),
('procept-biorobotics','Procept Biorobotics'),
('ptw-freiburg-lorracher-str-7-freiburg-im-breisgau-germany','Ptw-Freiburg Lorracher'),
('puritan-products','Puritan Products'),
('pyrames','Pyrames'),
('qiagen-sciences','Qiagen Sciences'),
('quanta-system-s-p-a-via-acquedotto-109-samarate-italy','Quanta System S P A Via Acquedotto'),
('quest-international','Quest International'),
('quidel','Quidel'),
('quidel-cardiovascular','Quidel Cardiovascular'),
('quidel-ortho','Quidel Ortho'),
('quidelortho','Quidelortho'),
('r-a-services-holmes-house-skipton-road-keighley-united-kingdom','R A Services Holmes House Skipton Road Keighley'),
('r-d','R & D'),
('radiometer-aps-akandevej-21-bronshoj-denmark','Radiometer'),
('rand-s-r-l-strada-statale-62-medolla-italy','Rand S R L Strada Statale 62 Medolla Italy'),
('randox-laboratories','Randox Laboratories'),
('randox-laboratories-ardmore-55-the-diamond-road-crumlin-united-kingdom','Randox Laboratories Ardmore; 55 The Diamond Road Crumlin'),
('raysearch-america','Raysearch America'),
('raysearch-laboratories-ab-sveavagen-9-stockholm-sweden','RaySearch'),
('raz-design','Raz Design'),
('reflexion','Reflexion'),
('remel','Remel'),
('remote-diagnostic-technologies-farnborough-aerospace-centre-aerospace-boulevard-farnborough-united-kingdom','Remote Diagnostic Technologies'),
('remote-diagnostic-technologies-pavilion-c2-ashwood-park-ashwood-way-basingstoke-united-kingdom','Remote Diagnostic Technologies'),
('resource-optimization-innovation','Resource Optimization & Innovation'),
('respironics-california','Respironics California'),
('retractable-technologies','Retractable Technologies'),
('richard-wolf-pforzheimer-str-32-knittlingen-germany','Richard Wolf'),
('riverpoint','Riverpoint'),
('roche-diabetes-care','Roche Diabetes Care'),
('roche-diagnostics-operations','Roche Diagnostics Operations'),
('s-mohr-america-de-c-v-circuito-de-la-industria-poniente-lote-10-c-estado-de-mexico-mexico','S & Mohr America De C V Circuito De La Industria Poniente Lote 10 C Estado De Mexico Mexico'),
('safe-orthopaedics','Safe Orthopaedics'),
('safeguard-us-operating','Safeguard Us Operating'),
('sage-products-3909-3-oaks-rd-cary-il-60013-1804','Sage Products'),
('sam-products','Sam Products'),
('saranas','Saranas'),
('sarnova-hc','Sarnova Hc'),
('schiller-altgasse-68-baar-switzerland','Schiller Altgasse 68 Baar'),
('scholly-fiberoptic-robert-bosch-str-1-3-denzlingen-germany','Scholly Fiberoptic Robert-Bosch-Str 1-3 Denzlingen'),
('science-bio-materials-zi-du-monge-lourdes-france','Science & Bio Materials Zi Du Monge Lourdes'),
('scientia-vascular','Scientia Vascular'),
('seaspine-orthopedics','Seaspine Orthopedics'),
('seer-278-284-queensberry-st-melbourne-australia','Seer'),
('sensory','Sensory'),
('sheathing-technologies','Sheathing Technologies'),
('shimadzu','Shimadzu'),
('shirakawa-olympus-azaokamiyama-3-1-oazaodakura-nishigo-mura-nishishirakawa-gun-japan','Shirakawa Olympus Azaokamiyama 3-1 Oazaodakura; Nishigo-Mura Nishishirakawa-Gun'),
('siemens-siemens-rittigfeld-1-forchheim-germany','Siemens /Siemens Rittigfeld 1 Forchheim'),
('sight-diagnostics-23-derekh-menakhem-begin-tel-aviv-yafo-israel','Sight Diagnostics'),
('sight-sciences','Sight Sciences'),
('simpleware-product-synopsys-northern-europe-bradninch-hall-castle-street-exeter-united-kingdom','Simpleware Product Synopsys Northern Europe Bradninch Hall Castle Street Exeter'),
('simplivia-north-ind-zone-migada-plant-north-ind-zone-pobox','Simplivia North Ind Zone (Migada Plant) North Ind Zone Pobox'),
('sin-sistema-de-implante-nacional-jardim-analia-franco-rua-soldador-ocimar-guimaraes-da-silva','Sin Sistema De Implante Nacional Jardim Analia Franco Rua Soldador Ocimar Guimaraes Da Silva'),
('sklar-instruments','Sklar Instruments'),
('skytron','Skytron'),
('skytron-div-the-kmw','Skytron Div The Kmw'),
('sleepnet','Sleepnet'),
('smith-nephew-orthopaedics-alemannenstr-14-tuttlingen-germany','Smith & Nephew Orthopaedics Alemannenstr 14 Tuttlingen'),
('smiths-asd','Smiths Asd'),
('soclean','Soclean'),
('sol-millennium','Sol-Millennium'),
('sonarmed','Sonarmed'),
('sonendo','Sonendo'),
('sonesta-ab-industrivagen','Sonesta Ab Industrivagen'),
('sophysa-rue-sophie-germain-besancon-france','Sophysa Rue Sophie Germain Besancon'),
('southmedic','Southmedic'),
('spacelabs-unit-b-foxholes-centre-john-tate-road-hertford-united-kingdom','Spacelabs Unit B Foxholes Centre; John Tate Road Hertford'),
('spark-biomedical','Spark Biomedical'),
('spectranetics','Spectranetics'),
('spectrum-harrier-4-meteor-business-park-cheltenham-road-east-gloucester-united-kingdom','Spectrum Harrier 4 Meteor Business'),
('spiggle-theis-mt-lagerstr-11-dieburg-germany','Spiggle & Theis Mt Lagerstr 11 Dieburg'),
('spineart-chemin-du-pre-fleuri-3-plan-les-ouates-switzerland','Spineart'),
('st-jude','St Jude'),
('stanley-security-solutions','Stanley Security Solutions'),
('sterilmed','Sterilmed'),
('steris-hopkins-facility','Steris Hopkins Facility'),
('stradis','Stradis'),
('straight-smile','Straight Smile'),
('stratasys','Stratasys'),
('straumann','Straumann'),
('stryker-bohnackerweg-1-selzach-switzerland','Stryker'),
('stryker-communications','Stryker Communications'),
('stryker-division-of-stryker','Stryker Division Of Stryker'),
('stryker-instruments','Stryker Instruments'),
('stryker-instruments-div-of-stryker','Stryker Instruments Div Of Stryker'),
('stryker-leibinger-kg-botzinger-str-41-freiburg-im-breisgau-germany','Stryker'),
('stryker-orthopaedics','Stryker Orthopaedics'),
('stryker-spine','Stryker Spine'),
('stryker-sustainability-solutions','Stryker Sustainability Solutions'),
('summa-therapeutics','Summa Therapeutics'),
('sunmed','Sunmed'),
('sunrise-us','Sunrise (Us)'),
('sunstar','Sunstar'),
('surepulse-medicity-d6-thane-road-nottingham-united-kingdom','Surepulse Medicity D6 Thane Road Nottingham'),
('surgical-innovations-6-clayton-wood-bank-lds-leeds-united-kingdom','Surgical Innovations 6 Clayton Wood Bank Lds Leeds'),
('surgical-innovations-clayton-house-6-clayton-wood-rise-leeds-united-kingdom','Surgical Innovations Clayton House 6 Clayton Wood Rise Leeds'),
('surgical-specialties','Surgical Specialties'),
('surgical-theater','Surgical Theater'),
('synaptive','Synaptive'),
('synergetics','Synergetics'),
('synthes-products','Synthes () Products'),
('sysmex-america','Sysmex America'),
('t-a-g-products-kibbutz-gatton-gaaton-israel','T A G Products Kibbutz Gatton Gaaton'),
('t-g-eakin','T G Eakin'),
('tandem-diabetes-care','Tandem Diabetes Care'),
('tapemark','Tapemark'),
('technicality','Technicality'),
('technidata-387-avenue-jean-kuntzmann-montbonnot-st-martin-france','Technidata'),
('technomed-europe-amerikalaan-71-maastricht-airport-netherlands','Technomed'),
('tei-biosciences','Tei Biosciences'),
('teknimed-sas-zone-industrielle-montredone-11-rue-d-apollo-l-union-france','Teknimed Sas Zone Industrielle Montredone 11 Rue D Apollo L''Union'),
('telcare','Telcare'),
('teleflex-europe-ida-business-park-athlone-ireland','Teleflex Europe Ida Business'),
('terumo-cardiovascular','Terumo Cardiovascular'),
('texas-technology','Texas Technology'),
('the-anspach-effort','The Anspach Effort'),
('the-binding-site','The Binding Site'),
('the-metrix','The Metrix'),
('theken-companies','Theken Companies'),
('think-surgical','Think Surgical'),
('thommen-eschenweg-3-bettlach-switzerland','Thommen Eschenweg 3 Bettlach'),
('thor-photomedicine-2-anglo-office-park-units-1-67-white-lion-road-amersham-united-kingdom','Thor Photomedicine 2 Anglo Office'),
('thor-photomedicine-watermeadow-house-chesham-united-kingdom','Thor Photomedicine Watermeadow House Chesham'),
('thoratec','Thoratec'),
('tisport','Tisport'),
('tobii-dynavox','Tobii Dynavox'),
('tomy-international','Tomy International'),
('tornier-s-161-rue-lavoisier-montbonnot-saint-martin-france','Tornier'),
('tornier-s-161-rue-lavoisier-montbonnot-st-martin-france','Tornier'),
('total-joint-orthopedics','Total Joint Orthopedics'),
('touch-us','Touch Us'),
('townsend-design','Townsend Design'),
('trackx-technology','Trackx Technology'),
('treace-concepts','Treace Concepts'),
('trexo-robotics','Trexo Robotics'),
('trimed','Trimed'),
('trinity-biotech','Trinity Biotech'),
('trinity-sterile','Trinity Sterile'),
('trividia','Trividia'),
('trokamed-kleine-breite-17-geisingen-germany','Trokamed Kleine Breite 17 Geisingen'),
('trophy-sas-trophy-sas-trophy-croissy-beaubourg','Trophy Sas Trophy Sas Trophy; Croissy Beaubourg'),
('truabutment','Truabutment'),
('turbett-surgical','Turbett Surgical'),
('turkuaz-saglik-hizmetleri-medikal-temizlik-kim-ur-san-ve-tic-a-s-akcaburgaz-mahallesi-muhsin-yazicioglu-caddesi-no-45-5-esenyurt-turkey','Turkuaz Saglik Hizmetleri Medikal Temizlik Kim Ur San Ve Tic A S Akcaburgaz Mahallesi Muhsin Yazicioglu Caddesi No:45/5 Esenyurt Turkey'),
('turncare','Turncare'),
('tyber','Tyber'),
('ufsk-international-osys-kirchhoffstr-1-ratisbon-germany','Ufsk International Osys Kirchhoffstr 1 Ratisbon'),
('ultra-clean','Ultra Clean'),
('ultradent-products','Ultradent Products'),
('unetixs-vascular','Unetixs Vascular'),
('unimax-8f-2-no','Unimax 8F-2 No'),
('united-orthopedic-no','United Orthopedic No'),
('unomedical-a-s-aaholmvej','Unomedical A/S Aaholmvej'),
('unomedical-a-s-osted-aholmvej-1','Unomedical A/S Osted Aholmvej 1'),
('us-endodontics','Us Endodontics'),
('vantive-us','Vantive Us'),
('vapotherm','Vapotherm'),
('varian-imaging-laboratory-tafernstrasse-7-dattwil-baden-switzerland','Varian Imaging Laboratory Tafernstrasse 7 Dattwil Baden'),
('vascutek-newmains-avenue-inchinnan-united-kingdom','Vascutek Newmains Avenue Inchinnan'),
('velano-vascular','Velano Vascular'),
('ventana','Ventana'),
('ventec-life','Ventec Life'),
('verathon','Verathon'),
('vero-biotech','Vero Biotech'),
('viewray','Viewray'),
('virtual-incision','Virtual Incision'),
('virtual-radiologic','Virtual Radiologic'),
('visgeneer-no-335-zhong-hua-rd-sec-6-xiangshan-dist-hsinchu-city-taiwan','Visgeneer No'),
('vision-rt-dove-house-arcadia-avenue-london-united-kingdom','Vision Rt Dove House Arcadia Avenue London'),
('visionsense-20-ha-magshimim-petakh-tikva-israel','Visionsense 20 Ha-Magshimim Petakh Tikva'),
('voco-anton-flettner-str-1-3-cuxhaven-germany','Voco Anton-Flettner-Str 1-3 Cuxhaven'),
('volcano','Volcano'),
('vortex-surgical','Vortex Surgical'),
('vyaire','Vyaire'),
('vyaire-leibnizstr-7-hochberg-germany','Vyaire Leibnizstr 7 Hochberg'),
('w-h-dentalwerk-buermoos-ignaz-glaser-strase-53-53-ignaz-glaser-strasse-buermoos-austria','W & H Dentalwerk Buermoos Ignaz Glaser Strase 53 53 Ignaz-Glaser-Strasse Buermoos Austria'),
('waismed-11-galgalei-ha-plada-pob-12135-herzliya-israel','Waismed 11 Galgalei Ha-Plada Pob'),
('waldemar-link-kg-hq-barkhausenweg-10-hamburg-germany','Waldemar Link'),
('waldemar-link-kg-mfg-site-ost-str-4-10-norderstedt-germany','Waldemar Link'),
('waldemar-link-kg-mfg-site-oststr-4-10-norderstedt-germany','Waldemar Link'),
('wandercraft-sas','Wandercraft Sas'),
('welch-allyn','Welch Allyn'),
('welch-allyn-mortara','Welch Allyn Mortara'),
('west-pharmaceutical-services-az','West Pharmaceutical Services Az'),
('western-scott-fetzer','Western/Scott Fetzer'),
('westmed','Westmed'),
('whele-dba-perch','Whele Dba Perch'),
('wingderm-electro-optics-room-312-building-d-3-dongsheng-science-park-no-66-of-xixiaokou-road-haidian-district-beijing-china','Wingderm Electro-Optics Room'),
('wissner-bosserhoff-hauptstr-4-6-wickede-ruhr-germany','Wissner-Bosserhoff Hauptstr 4-6 Wickede (Ruhr)'),
('withings-37-bis-rue-du-general-leclerc-issy-les-moulineaux-cedex-france','Withings 37 Bis Rue Du General Leclerc Issy Les Moulineaux Cedex'),
('wolf-henke-sass-kronenstrasse-16-tuttlingen-germany','Wolf Henke Sass Kronenstrasse 16 Tuttlingen'),
('wom-world-of-medicine-alte-poststr-11-ludwigsstadt-germany','Wom World Of Medicine Alte Poststr 11 Ludwigsstadt'),
('wom-world-of-medicine-salzufer-8-berlin-germany','Wom World Of Medicine Salzufer 8 Berlin'),
('wright-technology','Wright Technology'),
('xcision','Xcision'),
('xenex-disinfection-services','Xenex Disinfection Services'),
('young-dental-manufacturing-i','Young Dental Manufacturing I'),
('young-dental-mfg-i','Young Dental Mfg I'),
('zap-surgical','Zap Surgical'),
('zeiss-carl','Zeiss Carl'),
('zeltiq-aesthetics','Zeltiq Aesthetics'),
('zhejiang-luyao-electronics-technology-pingyang-county-wenzhou-china','Zhejiang Luyao Electronics Technology Pingyang County Wenzhou'),
('zimmer','Zimmer'),
('zimmer-biomet-spine','Zimmer Biomet Spine'),
('zimmer-orthopedics-manfacturing-galway-deerpark-industrial-estate-oranmore-ireland','Zimmer'),
('zimmer-sulzerallee-8-winterthur-switzerland','Zimmer'),
('zyno','Zyno')
)
update public.recall_manufacturers rm
set
  is_commercial_manufacturer = true,
  cl_search_name = a.cl_search_name
from allow a
where rm.slug = a.slug;

-- Sanity: default cl_search_name to canonical_name where still null on approved
update public.recall_manufacturers
set cl_search_name = canonical_name
where is_commercial_manufacturer = true and cl_search_name is null;
