-- Full-Nielsen dma_markets seed (129 missing DMAs) + pi_metros DMA crosswalk.
-- Generated by scripts/gen_dma_markets_seed.py from the simzou Nielsen gist (tv.json).
-- Existing 81 verified rows are preserved (ON CONFLICT DO NOTHING). Phase 1 / Competitive Analysis.

INSERT INTO public.dma_markets (dma_code, display_name, full_name, primary_state, states_covered, population, rank) VALUES
  ('500', 'Portland ME', 'Portland-Auburn', 'ME', ARRAY['ME'], 973825, 80),
  ('502', 'Binghamton', 'Binghamton', 'NY', ARRAY['NY','PA'], 333550, 157),
  ('509', 'Fort Wayne', 'Ft. Wayne', 'IN', ARRAY['IN'], 663475, 109),
  ('512', 'Baltimore', 'Baltimore', 'MD', ARRAY['MD'], 2712675, 27),
  ('521', 'Providence', 'Providence-New Bedford', 'RI', ARRAY['RI','MA'], 1516000, 53),
  ('523', 'Burlington', 'Burlington-Plattsburgh', 'VT', ARRAY['VT','NY'], 792275, 97),
  ('526', 'Utica', 'Utica', 'NY', ARRAY['NY'], 257225, 172),
  ('529', 'Louisville', 'Louisville', 'KY', ARRAY['KY','IN'], 1677200, 48),
  ('532', 'Albany NY', 'Albany-Schenectady-Troy', 'NY', ARRAY['NY'], 1350125, 58),
  ('536', 'Youngstown', 'Youngstown', 'OH', ARRAY['OH','PA'], 650000, 110),
  ('537', 'Bangor', 'Bangor', 'ME', ARRAY['ME'], 345100, 155),
  ('538', 'Rochester NY', 'Rochester, NY', 'NY', ARRAY['NY'], 989200, 78),
  ('540', 'Traverse City', 'Traverse City-Cadillac', 'MI', ARRAY['MI'], 604500, 119),
  ('541', 'Lexington', 'Lexington', 'KY', ARRAY['KY'], 1214075, 64),
  ('543', 'Springfield MA', 'Springfield-Holyoke', 'MA', ARRAY['MA'], 632375, 114),
  ('544', 'Norfolk', 'Norfolk-Portsmth-Newpt Nws', 'VA', ARRAY['VA','NC'], 1774325, 44),
  ('545', 'Greenville NC', 'Greenville-N.Bern-Washngtn', 'NC', ARRAY['NC'], 758200, 100),
  ('546', 'Columbia SC', 'Columbia, SC', 'SC', ARRAY['SC'], 996275, 77),
  ('549', 'Watertown', 'Watertown', 'NY', ARRAY['NY'], 231475, 177),
  ('550', 'Wilmington NC', 'Wilmington', 'NC', ARRAY['NC'], 471050, 132),
  ('551', 'Lansing', 'Lansing', 'MI', ARRAY['MI'], 627850, 115),
  ('552', 'Presque Isle', 'Presque Isle', 'ME', ARRAY['ME'], 73125, 205),
  ('554', 'Wheeling', 'Wheeling-Steubenville', 'WV', ARRAY['WV','OH'], 325275, 158),
  ('556', 'Richmond', 'Richmond-Petersburg', 'VA', ARRAY['VA'], 1383475, 57),
  ('558', 'Lima', 'Lima', 'OH', ARRAY['OH'], 128100, 199),
  ('559', 'Bluefield', 'Bluefield-Beckley-Oak Hill', 'WV', ARRAY['WV','VA'], 336025, 156),
  ('564', 'Charleston WV', 'Charleston-Huntington', 'WV', ARRAY['WV'], 1138725, 65),
  ('565', 'Elmira', 'Elmira (Corning)', 'NY', ARRAY['NY'], 238825, 174),
  ('567', 'Greenville SC', 'Greenvll-Spart-Ashevll-And', 'SC', ARRAY['SC','NC'], 2115075, 37),
  ('569', 'Harrisonburg', 'Harrisonburg', 'VA', ARRAY['VA'], 225650, 178),
  ('570', 'Myrtle Beach', 'Myrtle Beach-Florence', 'SC', ARRAY['SC'], 713875, 103),
  ('573', 'Roanoke', 'Roanoke-Lynchburg', 'VA', ARRAY['VA'], 1113675, 68),
  ('576', 'Salisbury', 'Salisbury', 'MD', ARRAY['MD','DE','VA'], 394575, 144),
  ('581', 'Terre Haute', 'Terre Haute', 'IN', ARRAY['IN'], 349000, 154),
  ('583', 'Alpena', 'Alpena', 'MI', ARRAY['MI'], 42275, 208),
  ('584', 'Charlottesville', 'Charlottesville', 'VA', ARRAY['VA'], 185850, 183),
  ('588', 'South Bend', 'South Bend-Elkhart', 'IN', ARRAY['IN'], 799650, 95),
  ('596', 'Zanesville', 'Zanesville', 'OH', ARRAY['OH'], 82350, 203),
  ('597', 'Parkersburg', 'Parkersburg', 'WV', ARRAY['WV','OH'], 156550, 193),
  ('598', 'Clarksburg', 'Clarksburg-Weston', 'WV', ARRAY['WV'], 266200, 170),
  ('603', 'Joplin', 'Joplin-Pittsburg', 'MO', ARRAY['MO','KS'], 378000, 149),
  ('604', 'Columbia MO', 'Columbia-Jefferson City', 'MO', ARRAY['MO'], 434100, 138),
  ('605', 'Topeka', 'Topeka', 'KS', ARRAY['KS'], 440400, 136),
  ('606', 'Dothan', 'Dothan', 'AL', ARRAY['AL'], 267775, 169),
  ('609', 'St. Louis', 'St. Louis', 'MO', ARRAY['MO','IL'], 3108725, 21),
  ('610', 'Rockford', 'Rockford', 'IL', ARRAY['IL'], 448100, 135),
  ('611', 'Rochester MN', 'Rochestr-Mason City-Austin', 'MN', ARRAY['MN','IA'], 358325, 153),
  ('612', 'Shreveport', 'Shreveport', 'LA', ARRAY['LA'], 961025, 82),
  ('616', 'Kansas City', 'Kansas City', 'MO', ARRAY['MO','KS'], 2328300, 31),
  ('617', 'Milwaukee', 'Milwaukee', 'WI', ARRAY['WI'], 2255475, 34),
  ('619', 'Springfield MO', 'Springfield, MO', 'MO', ARRAY['MO'], 1036425, 74),
  ('622', 'New Orleans', 'New Orleans', 'LA', ARRAY['LA'], 1603875, 51),
  ('624', 'Sioux City', 'Sioux City', 'IA', ARRAY['IA','NE','SD'], 387075, 147),
  ('625', 'Waco', 'Waco-Temple-Bryan', 'TX', ARRAY['TX'], 873850, 88),
  ('626', 'Victoria', 'Victoria', 'TX', ARRAY['TX'], 78900, 204),
  ('627', 'Wichita Falls', 'Wichita Falls & Lawton', 'TX', ARRAY['TX','OK'], 396250, 143),
  ('628', 'Monroe', 'Monroe-El Dorado', 'LA', ARRAY['LA','AR'], 439900, 137),
  ('631', 'Ottumwa', 'Ottumwa-Kirksville', 'IA', ARRAY['IA','MO'], 116825, 200),
  ('632', 'Paducah', 'Paducah-Cape Girard-Harsbg', 'KY', ARRAY['KY','IL','MO','TN'], 970850, 81),
  ('633', 'Odessa-Midland', 'Odessa-Midland', 'TX', ARRAY['TX'], 369325, 152),
  ('634', 'Amarillo', 'Amarillo', 'TX', ARRAY['TX'], 492775, 130),
  ('636', 'Harlingen', 'Harlingen-Wslco-Brnsvl-McA', 'TX', ARRAY['TX'], 910400, 86),
  ('637', 'Cedar Rapids', 'Cedar Rapids-Wtrlo-IWC&Dub', 'IA', ARRAY['IA'], 856525, 90),
  ('638', 'St. Joseph', 'St. Joseph', 'MO', ARRAY['MO'], 115450, 201),
  ('642', 'Lafayette LA', 'Lafayette, LA', 'LA', ARRAY['LA'], 573300, 124),
  ('643', 'Lake Charles', 'Lake Charles', 'LA', ARRAY['LA'], 236525, 175),
  ('644', 'Alexandria LA', 'Alexandria, LA', 'LA', ARRAY['LA'], 223200, 179),
  ('647', 'Greenwood', 'Greenwood-Greenville', 'MS', ARRAY['MS'], 166025, 188),
  ('649', 'Evansville', 'Evansville', 'IN', ARRAY['IN','KY','IL'], 710100, 104),
  ('650', 'Oklahoma City', 'Oklahoma City', 'OK', ARRAY['OK'], 1796925, 41),
  ('651', 'Lubbock', 'Lubbock', 'TX', ARRAY['TX'], 399600, 142),
  ('652', 'Omaha', 'Omaha', 'NE', ARRAY['NE','IA'], 1035150, 75),
  ('657', 'Sherman', 'Sherman-Ada', 'TX', ARRAY['TX','OK'], 317325, 161),
  ('658', 'Green Bay', 'Green Bay-Appleton', 'WI', ARRAY['WI'], 1104500, 69),
  ('661', 'San Angelo', 'San Angelo', 'TX', ARRAY['TX'], 139550, 196),
  ('662', 'Abilene', 'Abilene-Sweetwater', 'TX', ARRAY['TX'], 285200, 164),
  ('669', 'Madison', 'Madison', 'WI', ARRAY['WI'], 941675, 85),
  ('670', 'Fort Smith', 'Ft. Smith-Fay-Sprngdl-Rgrs', 'AR', ARRAY['AR','OK'], 743975, 101),
  ('671', 'Tulsa', 'Tulsa', 'OK', ARRAY['OK'], 1317400, 59),
  ('673', 'Columbus MS', 'Columbus-Tupelo-W Pnt-Hstn', 'MS', ARRAY['MS'], 462475, 133),
  ('676', 'Duluth', 'Duluth-Superior', 'MN', ARRAY['MN','WI'], 424025, 139),
  ('678', 'Wichita', 'Wichita-Hutchinson Plus', 'KS', ARRAY['KS'], 1125750, 66),
  ('679', 'Des Moines', 'Des Moines-Ames', 'IA', ARRAY['IA'], 1069650, 72),
  ('682', 'Davenport', 'Davenport-R.Island-Moline', 'IA', ARRAY['IA','IL'], 759500, 99),
  ('687', 'Minot-Bismarck', 'Minot-Bsmrck-Dcknsn(Wlstn)', 'ND', ARRAY['ND'], 375000, 151),
  ('693', 'Little Rock', 'Little Rock-Pine Bluff', 'AR', ARRAY['AR'], 1404400, 56),
  ('702', 'La Crosse', 'La Crosse-Eau Claire', 'WI', ARRAY['WI','MN'], 529175, 128),
  ('705', 'Wausau', 'Wausau-Rhinelander', 'WI', ARRAY['WI'], 448625, 134),
  ('710', 'Hattiesburg', 'Hattiesburg-Laurel', 'MS', ARRAY['MS'], 274875, 167),
  ('711', 'Meridian', 'Meridian', 'MS', ARRAY['MS'], 172150, 186),
  ('716', 'Baton Rouge', 'Baton Rouge', 'LA', ARRAY['LA'], 824050, 94),
  ('717', 'Quincy', 'Quincy-Hannibal-Keokuk', 'IL', ARRAY['IL','MO','IA'], 258800, 171),
  ('718', 'Jackson MS', 'Jackson, MS', 'MS', ARRAY['MS'], 828750, 93),
  ('722', 'Lincoln', 'Lincoln & Hastings-Krny', 'NE', ARRAY['NE'], 691975, 105),
  ('724', 'Fargo', 'Fargo-Valley City', 'ND', ARRAY['ND','MN'], 609725, 117),
  ('725', 'Sioux Falls', 'Sioux Falls(Mitchell)', 'SD', ARRAY['SD'], 646150, 112),
  ('734', 'Jonesboro', 'Jonesboro', 'AR', ARRAY['AR'], 201850, 181),
  ('736', 'Bowling Green', 'Bowling Green', 'KY', ARRAY['KY'], 196950, 182),
  ('737', 'Mankato', 'Mankato', 'MN', ARRAY['MN'], 131325, 198),
  ('740', 'North Platte', 'North Platte', 'NE', ARRAY['NE'], 36800, 209),
  ('743', 'Anchorage', 'Anchorage', 'AK', ARRAY['AK'], 390700, 145),
  ('744', 'Honolulu', 'Honolulu', 'HI', ARRAY['HI'], 1094475, 71),
  ('745', 'Fairbanks', 'Fairbanks', 'AK', ARRAY['AK'], 94800, 202),
  ('746', 'Biloxi-Gulfport', 'Biloxi-Gulfport', 'MS', ARRAY['MS'], 320750, 160),
  ('747', 'Juneau', 'Juneau', 'AK', ARRAY['AK'], 65800, 207),
  ('749', 'Laredo', 'Laredo', 'TX', ARRAY['TX'], 181475, 184),
  ('752', 'Colorado Springs', 'Colorado Springs-Pueblo', 'CO', ARRAY['CO'], 859975, 89),
  ('754', 'Butte-Bozeman', 'Butte-Bozeman', 'MT', ARRAY['MT'], 167950, 187),
  ('755', 'Great Falls', 'Great Falls', 'MT', ARRAY['MT'], 164825, 190),
  ('756', 'Billings', 'Billings', 'MT', ARRAY['MT'], 274325, 168),
  ('757', 'Boise', 'Boise', 'ID', ARRAY['ID'], 647725, 111),
  ('758', 'Idaho Falls', 'Idaho Fals-Pocatllo(Jcksn)', 'ID', ARRAY['ID','WY'], 314275, 162),
  ('759', 'Cheyenne', 'Cheyenne-Scottsbluff', 'WY', ARRAY['WY','NE'], 140875, 195),
  ('760', 'Twin Falls', 'Twin Falls', 'ID', ARRAY['ID'], 160250, 191),
  ('762', 'Missoula', 'Missoula', 'MT', ARRAY['MT'], 282525, 166),
  ('764', 'Rapid City', 'Rapid City', 'SD', ARRAY['SD'], 245050, 173),
  ('766', 'Helena', 'Helena', 'MT', ARRAY['MT'], 70650, 206),
  ('767', 'Casper', 'Casper-Riverton', 'WY', ARRAY['WY'], 138175, 197),
  ('770', 'Salt Lake City', 'Salt Lake City', 'UT', ARRAY['UT'], 2293425, 33),
  ('773', 'Grand Junction', 'Grand Junction-Montrose', 'CO', ARRAY['CO'], 176450, 185),
  ('790', 'Albuquerque', 'Albuquerque-Santa Fe', 'NM', ARRAY['NM'], 1728625, 47),
  ('798', 'Glendive', 'Glendive', 'MT', ARRAY['MT'], 10125, 210),
  ('801', 'Eugene', 'Eugene', 'OR', ARRAY['OR'], 588925, 121),
  ('810', 'Yakima', 'Yakima-Pasco-Rchlnd-Knnwck', 'WA', ARRAY['WA'], 579875, 122),
  ('811', 'Reno', 'Reno', 'NV', ARRAY['NV'], 664000, 108),
  ('813', 'Medford', 'Medford-Klamath Falls', 'OR', ARRAY['OR'], 419550, 140),
  ('821', 'Bend', 'Bend, OR', 'OR', ARRAY['OR'], 157375, 192),
  ('839', 'Las Vegas', 'Las Vegas', 'NV', ARRAY['NV'], 1797475, 40),
  ('881', 'Spokane', 'Spokane', 'WA', ARRAY['WA','ID'], 1051600, 73)
ON CONFLICT (dma_code) DO NOTHING;

-- pi_metros city -> DMA crosswalk (idempotent; overwrites the principal-city name-match).
UPDATE public.pi_metros SET dma_code = '743' WHERE state_abbr = 'AK' AND metro_name = 'Anchorage';
UPDATE public.pi_metros SET dma_code = '745' WHERE state_abbr = 'AK' AND metro_name = 'Fairbanks';
UPDATE public.pi_metros SET dma_code = '747' WHERE state_abbr = 'AK' AND metro_name = 'Juneau';
UPDATE public.pi_metros SET dma_code = '630' WHERE state_abbr = 'AL' AND metro_name = 'Birmingham';
UPDATE public.pi_metros SET dma_code = '691' WHERE state_abbr = 'AL' AND metro_name = 'Huntsville';
UPDATE public.pi_metros SET dma_code = '686' WHERE state_abbr = 'AL' AND metro_name = 'Mobile';
UPDATE public.pi_metros SET dma_code = '698' WHERE state_abbr = 'AL' AND metro_name = 'Montgomery';
UPDATE public.pi_metros SET dma_code = '670' WHERE state_abbr = 'AR' AND metro_name = 'Fayetteville';
UPDATE public.pi_metros SET dma_code = '670' WHERE state_abbr = 'AR' AND metro_name = 'Fort Smith';
UPDATE public.pi_metros SET dma_code = '693' WHERE state_abbr = 'AR' AND metro_name = 'Little Rock';
UPDATE public.pi_metros SET dma_code = '753' WHERE state_abbr = 'AZ' AND metro_name = 'Mesa';
UPDATE public.pi_metros SET dma_code = '753' WHERE state_abbr = 'AZ' AND metro_name = 'Phoenix';
UPDATE public.pi_metros SET dma_code = '789' WHERE state_abbr = 'AZ' AND metro_name = 'Tucson';
UPDATE public.pi_metros SET dma_code = '771' WHERE state_abbr = 'AZ' AND metro_name = 'Yuma';
UPDATE public.pi_metros SET dma_code = '803' WHERE state_abbr = 'CA' AND metro_name = 'Los Angeles';
UPDATE public.pi_metros SET dma_code = '862' WHERE state_abbr = 'CA' AND metro_name = 'Sacramento';
UPDATE public.pi_metros SET dma_code = '825' WHERE state_abbr = 'CA' AND metro_name = 'San Diego';
UPDATE public.pi_metros SET dma_code = '807' WHERE state_abbr = 'CA' AND metro_name = 'San Francisco';
UPDATE public.pi_metros SET dma_code = '751' WHERE state_abbr = 'CO' AND metro_name = 'Aurora';
UPDATE public.pi_metros SET dma_code = '752' WHERE state_abbr = 'CO' AND metro_name = 'Colorado Springs';
UPDATE public.pi_metros SET dma_code = '751' WHERE state_abbr = 'CO' AND metro_name = 'Denver';
UPDATE public.pi_metros SET dma_code = '501' WHERE state_abbr = 'CT' AND metro_name = 'Bridgeport';
UPDATE public.pi_metros SET dma_code = '533' WHERE state_abbr = 'CT' AND metro_name = 'Hartford';
UPDATE public.pi_metros SET dma_code = '533' WHERE state_abbr = 'CT' AND metro_name = 'New Haven';
UPDATE public.pi_metros SET dma_code = '511' WHERE state_abbr = 'DC' AND metro_name = 'Washington';
UPDATE public.pi_metros SET dma_code = '504' WHERE state_abbr = 'DE' AND metro_name = 'Dover';
UPDATE public.pi_metros SET dma_code = '504' WHERE state_abbr = 'DE' AND metro_name = 'Newark';
UPDATE public.pi_metros SET dma_code = '504' WHERE state_abbr = 'DE' AND metro_name = 'Wilmington';
UPDATE public.pi_metros SET dma_code = '561' WHERE state_abbr = 'FL' AND metro_name = 'Jacksonville';
UPDATE public.pi_metros SET dma_code = '528' WHERE state_abbr = 'FL' AND metro_name = 'Miami';
UPDATE public.pi_metros SET dma_code = '534' WHERE state_abbr = 'FL' AND metro_name = 'Orlando';
UPDATE public.pi_metros SET dma_code = '539' WHERE state_abbr = 'FL' AND metro_name = 'Tampa';
UPDATE public.pi_metros SET dma_code = '524' WHERE state_abbr = 'GA' AND metro_name = 'Atlanta';
UPDATE public.pi_metros SET dma_code = '520' WHERE state_abbr = 'GA' AND metro_name = 'Augusta';
UPDATE public.pi_metros SET dma_code = '507' WHERE state_abbr = 'GA' AND metro_name = 'Savannah';
UPDATE public.pi_metros SET dma_code = '744' WHERE state_abbr = 'HI' AND metro_name = 'Hilo';
UPDATE public.pi_metros SET dma_code = '744' WHERE state_abbr = 'HI' AND metro_name = 'Honolulu';
UPDATE public.pi_metros SET dma_code = '744' WHERE state_abbr = 'HI' AND metro_name = 'Kailua';
UPDATE public.pi_metros SET dma_code = '637' WHERE state_abbr = 'IA' AND metro_name = 'Cedar Rapids';
UPDATE public.pi_metros SET dma_code = '682' WHERE state_abbr = 'IA' AND metro_name = 'Davenport';
UPDATE public.pi_metros SET dma_code = '679' WHERE state_abbr = 'IA' AND metro_name = 'Des Moines';
UPDATE public.pi_metros SET dma_code = '757' WHERE state_abbr = 'ID' AND metro_name = 'Boise';
UPDATE public.pi_metros SET dma_code = '757' WHERE state_abbr = 'ID' AND metro_name = 'Meridian';
UPDATE public.pi_metros SET dma_code = '757' WHERE state_abbr = 'ID' AND metro_name = 'Nampa';
UPDATE public.pi_metros SET dma_code = '602' WHERE state_abbr = 'IL' AND metro_name = 'Chicago';
UPDATE public.pi_metros SET dma_code = '610' WHERE state_abbr = 'IL' AND metro_name = 'Rockford';
UPDATE public.pi_metros SET dma_code = '648' WHERE state_abbr = 'IL' AND metro_name = 'Springfield';
UPDATE public.pi_metros SET dma_code = '649' WHERE state_abbr = 'IN' AND metro_name = 'Evansville';
UPDATE public.pi_metros SET dma_code = '509' WHERE state_abbr = 'IN' AND metro_name = 'Fort Wayne';
UPDATE public.pi_metros SET dma_code = '527' WHERE state_abbr = 'IN' AND metro_name = 'Indianapolis';
UPDATE public.pi_metros SET dma_code = '616' WHERE state_abbr = 'KS' AND metro_name = 'Overland Park';
UPDATE public.pi_metros SET dma_code = '605' WHERE state_abbr = 'KS' AND metro_name = 'Topeka';
UPDATE public.pi_metros SET dma_code = '678' WHERE state_abbr = 'KS' AND metro_name = 'Wichita';
UPDATE public.pi_metros SET dma_code = '736' WHERE state_abbr = 'KY' AND metro_name = 'Bowling Green';
UPDATE public.pi_metros SET dma_code = '541' WHERE state_abbr = 'KY' AND metro_name = 'Lexington';
UPDATE public.pi_metros SET dma_code = '529' WHERE state_abbr = 'KY' AND metro_name = 'Louisville';
UPDATE public.pi_metros SET dma_code = '716' WHERE state_abbr = 'LA' AND metro_name = 'Baton Rouge';
UPDATE public.pi_metros SET dma_code = '622' WHERE state_abbr = 'LA' AND metro_name = 'New Orleans';
UPDATE public.pi_metros SET dma_code = '612' WHERE state_abbr = 'LA' AND metro_name = 'Shreveport';
UPDATE public.pi_metros SET dma_code = '506' WHERE state_abbr = 'MA' AND metro_name = 'Boston';
UPDATE public.pi_metros SET dma_code = '543' WHERE state_abbr = 'MA' AND metro_name = 'Springfield';
UPDATE public.pi_metros SET dma_code = '506' WHERE state_abbr = 'MA' AND metro_name = 'Worcester';
UPDATE public.pi_metros SET dma_code = '512' WHERE state_abbr = 'MD' AND metro_name = 'Baltimore';
UPDATE public.pi_metros SET dma_code = '511' WHERE state_abbr = 'MD' AND metro_name = 'Frederick';
UPDATE public.pi_metros SET dma_code = '511' WHERE state_abbr = 'MD' AND metro_name = 'Rockville';
UPDATE public.pi_metros SET dma_code = '537' WHERE state_abbr = 'ME' AND metro_name = 'Bangor';
UPDATE public.pi_metros SET dma_code = '500' WHERE state_abbr = 'ME' AND metro_name = 'Lewiston';
UPDATE public.pi_metros SET dma_code = '500' WHERE state_abbr = 'ME' AND metro_name = 'Portland';
UPDATE public.pi_metros SET dma_code = '505' WHERE state_abbr = 'MI' AND metro_name = 'Ann Arbor';
UPDATE public.pi_metros SET dma_code = '505' WHERE state_abbr = 'MI' AND metro_name = 'Detroit';
UPDATE public.pi_metros SET dma_code = '563' WHERE state_abbr = 'MI' AND metro_name = 'Grand Rapids';
UPDATE public.pi_metros SET dma_code = '613' WHERE state_abbr = 'MN' AND metro_name = 'Minneapolis';
UPDATE public.pi_metros SET dma_code = '611' WHERE state_abbr = 'MN' AND metro_name = 'Rochester';
UPDATE public.pi_metros SET dma_code = '613' WHERE state_abbr = 'MN' AND metro_name = 'Saint Paul';
UPDATE public.pi_metros SET dma_code = '616' WHERE state_abbr = 'MO' AND metro_name = 'Kansas City';
UPDATE public.pi_metros SET dma_code = '619' WHERE state_abbr = 'MO' AND metro_name = 'Springfield';
UPDATE public.pi_metros SET dma_code = '609' WHERE state_abbr = 'MO' AND metro_name = 'St. Louis';
UPDATE public.pi_metros SET dma_code = '746' WHERE state_abbr = 'MS' AND metro_name = 'Gulfport';
UPDATE public.pi_metros SET dma_code = '718' WHERE state_abbr = 'MS' AND metro_name = 'Jackson';
UPDATE public.pi_metros SET dma_code = '640' WHERE state_abbr = 'MS' AND metro_name = 'Southaven';
UPDATE public.pi_metros SET dma_code = '756' WHERE state_abbr = 'MT' AND metro_name = 'Billings';
UPDATE public.pi_metros SET dma_code = '754' WHERE state_abbr = 'MT' AND metro_name = 'Bozeman';
UPDATE public.pi_metros SET dma_code = '762' WHERE state_abbr = 'MT' AND metro_name = 'Missoula';
UPDATE public.pi_metros SET dma_code = '517' WHERE state_abbr = 'NC' AND metro_name = 'Charlotte';
UPDATE public.pi_metros SET dma_code = '518' WHERE state_abbr = 'NC' AND metro_name = 'Greensboro';
UPDATE public.pi_metros SET dma_code = '560' WHERE state_abbr = 'NC' AND metro_name = 'Raleigh';
UPDATE public.pi_metros SET dma_code = '687' WHERE state_abbr = 'ND' AND metro_name = 'Bismarck';
UPDATE public.pi_metros SET dma_code = '724' WHERE state_abbr = 'ND' AND metro_name = 'Fargo';
UPDATE public.pi_metros SET dma_code = '724' WHERE state_abbr = 'ND' AND metro_name = 'Grand Forks';
UPDATE public.pi_metros SET dma_code = '652' WHERE state_abbr = 'NE' AND metro_name = 'Bellevue';
UPDATE public.pi_metros SET dma_code = '722' WHERE state_abbr = 'NE' AND metro_name = 'Lincoln';
UPDATE public.pi_metros SET dma_code = '652' WHERE state_abbr = 'NE' AND metro_name = 'Omaha';
UPDATE public.pi_metros SET dma_code = '506' WHERE state_abbr = 'NH' AND metro_name = 'Concord';
UPDATE public.pi_metros SET dma_code = '506' WHERE state_abbr = 'NH' AND metro_name = 'Manchester';
UPDATE public.pi_metros SET dma_code = '506' WHERE state_abbr = 'NH' AND metro_name = 'Nashua';
UPDATE public.pi_metros SET dma_code = '501' WHERE state_abbr = 'NJ' AND metro_name = 'Jersey City';
UPDATE public.pi_metros SET dma_code = '501' WHERE state_abbr = 'NJ' AND metro_name = 'Newark';
UPDATE public.pi_metros SET dma_code = '501' WHERE state_abbr = 'NJ' AND metro_name = 'Paterson';
UPDATE public.pi_metros SET dma_code = '790' WHERE state_abbr = 'NM' AND metro_name = 'Albuquerque';
UPDATE public.pi_metros SET dma_code = '765' WHERE state_abbr = 'NM' AND metro_name = 'Las Cruces';
UPDATE public.pi_metros SET dma_code = '790' WHERE state_abbr = 'NM' AND metro_name = 'Santa Fe';
UPDATE public.pi_metros SET dma_code = '839' WHERE state_abbr = 'NV' AND metro_name = 'Henderson';
UPDATE public.pi_metros SET dma_code = '839' WHERE state_abbr = 'NV' AND metro_name = 'Las Vegas';
UPDATE public.pi_metros SET dma_code = '811' WHERE state_abbr = 'NV' AND metro_name = 'Reno';
UPDATE public.pi_metros SET dma_code = '514' WHERE state_abbr = 'NY' AND metro_name = 'Buffalo';
UPDATE public.pi_metros SET dma_code = '501' WHERE state_abbr = 'NY' AND metro_name = 'New York';
UPDATE public.pi_metros SET dma_code = '538' WHERE state_abbr = 'NY' AND metro_name = 'Rochester';
UPDATE public.pi_metros SET dma_code = '515' WHERE state_abbr = 'OH' AND metro_name = 'Cincinnati';
UPDATE public.pi_metros SET dma_code = '510' WHERE state_abbr = 'OH' AND metro_name = 'Cleveland';
UPDATE public.pi_metros SET dma_code = '535' WHERE state_abbr = 'OH' AND metro_name = 'Columbus';
UPDATE public.pi_metros SET dma_code = '650' WHERE state_abbr = 'OK' AND metro_name = 'Norman';
UPDATE public.pi_metros SET dma_code = '650' WHERE state_abbr = 'OK' AND metro_name = 'Oklahoma City';
UPDATE public.pi_metros SET dma_code = '671' WHERE state_abbr = 'OK' AND metro_name = 'Tulsa';
UPDATE public.pi_metros SET dma_code = '801' WHERE state_abbr = 'OR' AND metro_name = 'Eugene';
UPDATE public.pi_metros SET dma_code = '820' WHERE state_abbr = 'OR' AND metro_name = 'Portland';
UPDATE public.pi_metros SET dma_code = '820' WHERE state_abbr = 'OR' AND metro_name = 'Salem';
UPDATE public.pi_metros SET dma_code = '504' WHERE state_abbr = 'PA' AND metro_name = 'Allentown';
UPDATE public.pi_metros SET dma_code = '504' WHERE state_abbr = 'PA' AND metro_name = 'Philadelphia';
UPDATE public.pi_metros SET dma_code = '508' WHERE state_abbr = 'PA' AND metro_name = 'Pittsburgh';
UPDATE public.pi_metros SET dma_code = '521' WHERE state_abbr = 'RI' AND metro_name = 'Cranston';
UPDATE public.pi_metros SET dma_code = '521' WHERE state_abbr = 'RI' AND metro_name = 'Providence';
UPDATE public.pi_metros SET dma_code = '521' WHERE state_abbr = 'RI' AND metro_name = 'Warwick';
UPDATE public.pi_metros SET dma_code = '519' WHERE state_abbr = 'SC' AND metro_name = 'Charleston';
UPDATE public.pi_metros SET dma_code = '546' WHERE state_abbr = 'SC' AND metro_name = 'Columbia';
UPDATE public.pi_metros SET dma_code = '567' WHERE state_abbr = 'SC' AND metro_name = 'Greenville';
UPDATE public.pi_metros SET dma_code = '725' WHERE state_abbr = 'SD' AND metro_name = 'Aberdeen';
UPDATE public.pi_metros SET dma_code = '764' WHERE state_abbr = 'SD' AND metro_name = 'Rapid City';
UPDATE public.pi_metros SET dma_code = '725' WHERE state_abbr = 'SD' AND metro_name = 'Sioux Falls';
UPDATE public.pi_metros SET dma_code = '557' WHERE state_abbr = 'TN' AND metro_name = 'Knoxville';
UPDATE public.pi_metros SET dma_code = '640' WHERE state_abbr = 'TN' AND metro_name = 'Memphis';
UPDATE public.pi_metros SET dma_code = '659' WHERE state_abbr = 'TN' AND metro_name = 'Nashville';
UPDATE public.pi_metros SET dma_code = '623' WHERE state_abbr = 'TX' AND metro_name = 'Dallas';
UPDATE public.pi_metros SET dma_code = '618' WHERE state_abbr = 'TX' AND metro_name = 'Houston';
UPDATE public.pi_metros SET dma_code = '641' WHERE state_abbr = 'TX' AND metro_name = 'San Antonio';
UPDATE public.pi_metros SET dma_code = '770' WHERE state_abbr = 'UT' AND metro_name = 'Provo';
UPDATE public.pi_metros SET dma_code = '770' WHERE state_abbr = 'UT' AND metro_name = 'Salt Lake City';
UPDATE public.pi_metros SET dma_code = '770' WHERE state_abbr = 'UT' AND metro_name = 'West Valley City';
UPDATE public.pi_metros SET dma_code = '544' WHERE state_abbr = 'VA' AND metro_name = 'Norfolk';
UPDATE public.pi_metros SET dma_code = '556' WHERE state_abbr = 'VA' AND metro_name = 'Richmond';
UPDATE public.pi_metros SET dma_code = '544' WHERE state_abbr = 'VA' AND metro_name = 'Virginia Beach';
UPDATE public.pi_metros SET dma_code = '523' WHERE state_abbr = 'VT' AND metro_name = 'Burlington';
UPDATE public.pi_metros SET dma_code = '523' WHERE state_abbr = 'VT' AND metro_name = 'Rutland';
UPDATE public.pi_metros SET dma_code = '523' WHERE state_abbr = 'VT' AND metro_name = 'South Burlington';
UPDATE public.pi_metros SET dma_code = '819' WHERE state_abbr = 'WA' AND metro_name = 'Seattle';
UPDATE public.pi_metros SET dma_code = '881' WHERE state_abbr = 'WA' AND metro_name = 'Spokane';
UPDATE public.pi_metros SET dma_code = '819' WHERE state_abbr = 'WA' AND metro_name = 'Tacoma';
UPDATE public.pi_metros SET dma_code = '658' WHERE state_abbr = 'WI' AND metro_name = 'Green Bay';
UPDATE public.pi_metros SET dma_code = '669' WHERE state_abbr = 'WI' AND metro_name = 'Madison';
UPDATE public.pi_metros SET dma_code = '617' WHERE state_abbr = 'WI' AND metro_name = 'Milwaukee';
UPDATE public.pi_metros SET dma_code = '564' WHERE state_abbr = 'WV' AND metro_name = 'Charleston';
UPDATE public.pi_metros SET dma_code = '564' WHERE state_abbr = 'WV' AND metro_name = 'Huntington';
UPDATE public.pi_metros SET dma_code = '598' WHERE state_abbr = 'WV' AND metro_name = 'Morgantown';
UPDATE public.pi_metros SET dma_code = '767' WHERE state_abbr = 'WY' AND metro_name = 'Casper';
UPDATE public.pi_metros SET dma_code = '759' WHERE state_abbr = 'WY' AND metro_name = 'Cheyenne';
UPDATE public.pi_metros SET dma_code = '759' WHERE state_abbr = 'WY' AND metro_name = 'Laramie';
