-- Competitor Alerts: alert_configs, alert_events, alert_known_advertisers

-- 1. Alert configurations (per-user, per-tenant)
CREATE TABLE alert_configs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id),
  user_id UUID NOT NULL REFERENCES auth.users(id),
  tort_slug TEXT NOT NULL,
  state_code TEXT,
  alert_name TEXT NOT NULL,
  is_active BOOLEAN DEFAULT true,
  email_enabled BOOLEAN DEFAULT true,
  in_app_enabled BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE alert_configs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own alerts"
  ON alert_configs
  FOR ALL
  USING (
    tenant_id = my_tenant_id()
    AND user_id = auth.uid()
  )
  WITH CHECK (
    tenant_id = my_tenant_id()
    AND user_id = auth.uid()
  );

CREATE INDEX idx_alert_configs_user ON alert_configs(user_id, is_active);
CREATE INDEX idx_alert_configs_tort_state ON alert_configs(tort_slug, state_code, is_active);

-- 2. Alert events (notifications generated by the check engine)
CREATE TABLE alert_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  alert_config_id UUID NOT NULL REFERENCES alert_configs(id) ON DELETE CASCADE,
  tenant_id UUID NOT NULL REFERENCES tenants(id),
  user_id UUID NOT NULL REFERENCES auth.users(id),
  event_type TEXT NOT NULL DEFAULT 'new_competitor',
  title TEXT NOT NULL,
  description TEXT,
  metadata JSONB DEFAULT '{}',
  is_read BOOLEAN DEFAULT false,
  email_sent BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE alert_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users see own alert events"
  ON alert_events
  FOR ALL
  USING (
    tenant_id = my_tenant_id()
    AND user_id = auth.uid()
  )
  WITH CHECK (
    tenant_id = my_tenant_id()
    AND user_id = auth.uid()
  );

CREATE INDEX idx_alert_events_user_unread ON alert_events(user_id, is_read, created_at DESC);
CREATE INDEX idx_alert_events_config ON alert_events(alert_config_id, created_at DESC);

-- 3. Known advertisers tracking (system-level, no RLS)
CREATE TABLE alert_known_advertisers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tort_slug TEXT NOT NULL,
  state_code TEXT,
  advertiser_id TEXT NOT NULL,
  advertiser_name TEXT NOT NULL,
  platform TEXT NOT NULL DEFAULT 'meta',
  first_seen_at TIMESTAMPTZ DEFAULT now(),
  last_seen_at TIMESTAMPTZ DEFAULT now(),
  ad_count INTEGER DEFAULT 1,
  metadata JSONB DEFAULT '{}',
  UNIQUE(tort_slug, state_code, advertiser_id, platform)
);

CREATE INDEX idx_known_advertisers_tort_state ON alert_known_advertisers(tort_slug, state_code, platform);
