/**
 * POST /api/strategy/export
 *
 * Stateless PPTX export for a standalone Strategy. The client posts back the
 * `Strategy` payload it already has; we map it to SlideSpec[] and reuse the
 * proposal-builder deck writer (pptxgenjs, native charts, Vercel-safe). Nothing
 * is persisted — the strategy is regenerated on demand.
 *
 * Errors: 400 invalid body · 401 unauth · 500 PPTX failure.
 */

import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { getAuthenticatedUser, resolveBrandingFromRequest } from "@/lib/proposal-builder/server";
import { buildProposalPptx } from "@/lib/proposal-builder/pptx";
import { standaloneStrategyToSlides, standaloneStrategyFilename } from "@/lib/strategy-engine/standalone-slides";
import type { Strategy } from "@/lib/strategy-engine/standalone";

export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  const supabase = await createClient();
  const auth = await getAuthenticatedUser(supabase);
  if (!auth) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  let body: Strategy;
  try {
    body = (await req.json()) as Strategy;
  } catch {
    return NextResponse.json({ error: "Request body must be JSON" }, { status: 400 });
  }
  if (!body?.recommendations || !body?.opportunity || !body?.market) {
    return NextResponse.json({ error: "Missing strategy payload" }, { status: 400 });
  }

  const branding = await resolveBrandingFromRequest(req);
  const slides = standaloneStrategyToSlides(body);

  let buffer: Buffer;
  try {
    buffer = await buildProposalPptx({
      title: `${body.market.label} ${(body.case_types ?? []).join(", ")} Media Strategy`,
      description: `${body.audience}-facing · generated by Legal Marketing Intelligence`,
      slides,
      branding,
    });
  } catch (e) {
    return NextResponse.json(
      { error: "PPTX generation failed", details: e instanceof Error ? e.message : String(e) },
      { status: 500 },
    );
  }

  const filename = standaloneStrategyFilename(body);
  return new NextResponse(new Uint8Array(buffer), {
    status: 200,
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Content-Length": String(buffer.length),
      "Cache-Control": "no-store",
    },
  });
}
