// AUTO-GENERATED by scripts/gen-state-county-geometry.mjs — do not edit by hand.
// Source: us-atlas counties-10m (US Census cartographic boundaries).
// State FIPS 11 · 1 counties · viewBox 700x870.

export interface CountyGeometry {
  /** County name with no "County" suffix, matching get_state_accident_summary.county. */
  name: string;
  /** SVG path 'd' attribute, projected into the viewBox below. */
  d: string;
}

export const VIEWBOX = { width: 700, height: 870 } as const;

export const COUNTY_GEOMETRY: CountyGeometry[] = [
  {
    "name": "District of Columbia",
    "d": "M12,263.2171188626671L256.75862068965216,12.08083228659234L384.96551724139135,134.08793908692314L688,435.30180098104756L268.4137931034493,857.9191677133495L256.75862068965216,657.430055833247L268.4137931034493,524.8896700423793Z"
  }
];
